### ISSUE TITLE
Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@10842c7e to handler EventHandler

### ISSUE THREAD

**Issue by mibby** [EngineHub/WorldEdit#1272]
WorldEdit-bukkit dev 4940 

Caused by this commit? https://github.com/EngineHub/WorldEdit/commit/cfd26253b6fb59ff6c65a0157a6780be7db4ea5a

Downgrading to dev 4934, all is fine.

```
[10:37:33] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@10842c7e to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:171) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$100(WorldEditPlugin.java:94) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:488) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Purpur-507]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:460) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:336) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:903) ~[patched_1.15.2.jar:git-Purpur-507]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 13 more
Caused by: java.lang.NoSuchMethodError: 'com.sk89q.worldedit.util.formatting.text.ComponentBuilder com.sk89q.worldedit.util.formatting.text.ComponentBuilder.mergeStyle(com.sk89q.worldedit.util.formatting.text.Component, java.util.Set)'
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.mergeStyle(TranslatableComponentRenderer.java:159) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.deepRender(TranslatableComponentRenderer.java:153) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderText(TranslatableComponentRenderer.java:113) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:48) ~[?:?]
	at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:175) ~[?:?]
	at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[?:?]
	at com.sk89q.worldedit.util.formatting.WorldEditText.reduceToText(WorldEditText.java:42) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitServerInterface.lambda$registerCommands$4(BukkitServerInterface.java:180) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitServerInterface.registerCommands(BukkitServerInterface.java:183) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.registerCommandsWith(PlatformCommandManager.java:445) ~[?:?]
	at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capability.java:58) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:187) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:300) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 13 more


[10:43:05] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.BlockInteractEvent@29f2bab3 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.WorldEdit.handleBlockLeftClick(WorldEdit.java:631) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:114) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Purpur-507]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Purpur-507]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:158) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1406) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1061) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Purpur-507]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:961) ~[patched_1.15.2.jar:git-Purpur-507]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 26 more
Caused by: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting PERMISSIONS
	at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:175) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.createProxyActor(PlatformManager.java:257) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:310) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 26 more
```

**Comment by wizjany** [comment]
not a worldedit issue so much as a CI issue. if you need to use recent builds for whatever reason you'll need to do a clean build and disable tests yourself.

**Comment by mibby** [comment]
Habit of staying up to date on the latest dev builds for testing, but sure. I'll wait until the CI is fixed then and just stay on dev 4934 for the time being.
