### ISSUE TITLE
InvocationTargetException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldEdit#1273]
**Versions**
Spigot 1.15.2 (Jenkins 2650)
WorldEdit-bukkit-7.2.0-b4943

**Describe the bug**

On server start-up:
```
[12:41:35] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[12:41:35] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@3a529c20 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:171) [WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$100(WorldEditPlugin.java:94) [WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:488) [WorldEdit-bukkit-7.2.0-b4943.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:442) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-03-24-0704:git-Spigot-a03b1fd-fc318cc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 17 more
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.formatting.text.ComponentBuilder.mergeStyle(Lcom/sk89q/worldedit/util/formatting/text/Component;Ljava/util/Set;)Lcom/sk89q/worldedit/util/formatting/text/ComponentBuilder;
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.mergeStyle(TranslatableComponentRenderer.java:159) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.deepRender(TranslatableComponentRenderer.java:153) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderText(TranslatableComponentRenderer.java:113) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:48) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:175) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.reduceToText(WorldEditText.java:42) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.lambda$registerCommands$4(BukkitServerInterface.java:180) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.registerCommands(BukkitServerInterface.java:183) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.registerCommandsWith(PlatformCommandManager.java:445) ~[?:?]
        at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capability.java:58) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:187) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:300) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 17 more
```

**Comment by wizjany** [comment]
#1272
