### ISSUE TITLE
Console Worldedit

### ISSUE THREAD

**Issue by Steev93** [EngineHub/WorldEdit#1299]
**Versions**
WorldEdit version: 7.1.1 Snapshot
Platform version: git-Paper-171

**Describe the bug**
Throws errors
```
>....       [23:04:33]: You need to provide a world (Try //world)
>....       [23:04:33]: You need to provide a world (Try //world)
>....       [23:04:33]: Set the world override to admin. (Use //world to go back to default)
>....       [23:04:33]: Please report this error: [See console]
>....       [23:04:33]: java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
>....      [23:04:33 ERROR: An unexpected error while handling a WorldEdit command ]
java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
    at com.sk89q.worldedit.EditSession.setBatchingChunks(EditSession.java:532) ~[?:?]
    at com.sk89q.worldedit.EditSession.enableStandardMode(EditSession.java:303) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_242]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
    at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
    at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
    at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
    at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
    at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
    at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
    at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
    at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:639) ~[?:?]
    at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:400) ~[?:?]
    at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
    at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
    at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:107) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:71) ~[?:?]
    at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:496) ~[?:?]
    at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-171]
    at it.mri.mycommand.Main.RunCommandsAsConsoleSender(Main.java:644) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.Execute(BlockListener.java:134) ~[?:?]
    at it.mri.mycommand.listener.BlockListener.onPlayerInteract(BlockListener.java:101) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor184.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-171]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-171]
    at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1122) ~[patched_1.15.2.jar:git-Paper-171]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Paper-171]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Expected behaviour**
Should be working... Run the command to remove blocks from the one location

So trying to select a button, to clear a 6*3 blocks away to Air. However after 4 hours of multiple commands no luck and really need your help!

Where I use it in MyCommand to run the commands below it selects the world but doesn't register that it has.

admin:
    x1200y28z-144:
      launchby: console
      command:
     - //world admin
      - //pos1 1273,24,-107
      - //pos2 1273,21,-102
      - //set air

**Screenshots**
http://prntscr.com/rze1mx
http://prntscr.com/rze360

**Additional context**
http://prntscr.com/rzdz5t

**Comment by wizjany** [comment]
Please reproduce without AWE.

**Comment by Steev93** [comment]
worked!
http://prntscr.com/rze9rv

Hmm, there is no way to keep AWE on and run this is there? I'd need to remove AWE

**Comment by wizjany** [comment]
Something you will have to bring up with the author of AWE. It's not our plugin and is known to break things all the time (as you can see).

**Comment by Steev93** [comment]
Indeed... Can you suggest anything else to lower the load of each Worldedit? So can just remove AWE? I hate it personally but helps with big things

**Comment by octylFractal** [comment]
The only other suggestion is to use `//watchdog` which will stop the server watchdog from crashing the server. It won't make the operation faster or async though. Async world access is unsafe.

**Comment by Steev93** [comment]
Will see how this goes this afternoon after work, while these work great and do the job I may have to remove AWE if they cannot fix this issue
