### ISSUE TITLE
Worldedit bug (Java error code) when adding an additional pludin

### ISSUE THREAD

**Issue by AxelFB-L3F** [EngineHub/WorldEdit#1330]
**Versions**
WorldEdit version: 7.1.0
Platform version: Bukkit

**Describe the bug**
> Hello, I'm french : I translate my message by google translate ;) thanks

Hello, when I add an additional plugin, at times my worldedit no longer works (I can still use the selection with the ax) and the plugin sends me the message (in the following image) during execution of the command `// set stone` for example ...

![chat message](https://user-images.githubusercontent.com/55553513/80920690-ba9e9f80-8d71-11ea-9c2e-855b168b09d5.png)

And the console ;

>.>.... [11:23:00 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: com.sk89q.util.StringUtil.parseListInQuotes([Ljava/lang/String;CCCZ)Ljava/util/List;
at com.sk89q.worldedit.extension.factory.parser.pattern.RandomPatternParser.parseFromInput(RandomPatternParser.java:67) ~[?:?]
at com.sk89q.worldedit.extension.factory.parser.pattern.RandomPatternParser.parseFromInput(RandomPatternParser.java:33) ~[?:?]
at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:73) ~[?:?]
at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:127) ~[?:?]
at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:498) ~[?:?]
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_212]
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_212]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_212]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_212]
at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:493) ~[?:?]
at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:430) ~[?:?]
at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:341) ~[?:?]
at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:490) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:349) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:50) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:702) ~[patched_1.15.2.jar:git-Paper-86]
at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-86]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-86]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-86]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-86]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**To Reproduce**

1. Add a new plugin on my server ([protocolLib](https://www.spigotmc.org/resources/protocollib.1997/) or [color-chat](https://dev.bukkit.org/projects/color-chat) or [dynmap](https://dev.bukkit.org/projects/dynmap))
2. Execute command `//set stone` for exemple (after the selection)

**Expected behavior**

That stone replaces the selected area (instead of an error message)

**Screenshots**

Already done (-> sorry to have done it instead)

**Additional context**

This error message occurred the 1st time when I had about 48 total plugins on my Minecraft server (I think this information useless)

**THANKS YOU ;)**
**Help me please...**
**Bye !**

**Comment by wizjany** [comment]
Support questions should go to discord.

**Comment by AxelFB-L3F** [comment]
Ok, thanks
