### ISSUE TITLE
InvocationTargetException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldEdit#1345]
**Versions**

WorldEdit version: 7.2.0-b5010
Platform version: Spigot 1.152 (Jenkins 2686)

**Describe the bug**
```
[06:11:14] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[06:11:14] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@4431f9b to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:171) [WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.access$100(WorldEditPlugin.java:94) [WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:483) [WorldEdit-bukkit-7.2.0-b5010.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:442) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-05-09-0558:git-Spigot-2f5d615-d07a78b]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 17 more
Caused by: java.lang.NullPointerException
        at com.sk89q.worldedit.util.translation.TranslationManager.loadTranslationFile(TranslationManager.java:111) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.tryLoadTranslations(TranslationManager.java:141) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.getTranslationMap(TranslationManager.java:162) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.tryLoadTranslations(TranslationManager.java:139) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.getTranslationMap(TranslationManager.java:162) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.lambda$new$0(TranslationManager.java:73) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer$1.translation(TranslatableComponentRenderer.java:57) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderTranslatable(TranslatableComponentRenderer.java:118) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:50) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.lambda$deepRender$0(TranslatableComponentRenderer.java:154) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.deepRender(TranslatableComponentRenderer.java:154) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderText(TranslatableComponentRenderer.java:113) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:48) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.lambda$deepRender$0(TranslatableComponentRenderer.java:154) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.deepRender(TranslatableComponentRenderer.java:154) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderText(TranslatableComponentRenderer.java:113) ~[?:?]
        at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:48) ~[?:?]
        at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:174) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[?:?]
        at com.sk89q.worldedit.util.formatting.WorldEditText.reduceToText(WorldEditText.java:42) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.lambda$registerCommands$4(BukkitServerInterface.java:182) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.registerCommands(BukkitServerInterface.java:185) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.registerCommandsWith(PlatformCommandManager.java:445) ~[?:?]
        at com.sk89q.worldedit.extension.platform.Capability$2.initialize(Capability.java:58) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.choosePreferred(PlatformManager.java:187) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlatformReady(PlatformManager.java:300) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 17 more
```

**To Reproduce**

1. Update to WE 7.2.0-b5010 (from WE 7.2.0-b5007); no other changes to configuration or platform
2. Start server

**Comment by SlimeDog** [comment]
Confirmed fixed in 7.2.0-b5011. Thanks.
