### ISSUE TITLE
Paste fails

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldEdit#1375]
**Versions**

WorldEdit version: 7.2.0-SNAPSHOT+5071-3db43c8
Platform version: Spigot 1.15.2

**Describe the bug**

Pasting a selection produces errors and doesn't paste content
```
[21:05:32] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@dba643 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:349) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[?:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[?:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-06-23-1736:git-Spigot-a99063f-be6aaf0]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 21 more
Caused by: java.lang.AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.WorldNativeAccess_v1_15_R2 does not define or inherit an implementation of the resolved method abstract updateNeighbors(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;I)V of interface com.sk89q.worldedit.internal.wna.WorldNativeAccess.
        at com.sk89q.worldedit.internal.wna.WorldNativeAccess.markAndNotifyBlock(WorldNativeAccess.java:178) ~[?:?]
        at com.sk89q.worldedit.internal.wna.WorldNativeAccess.setBlock(WorldNativeAccess.java:87) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:443) ~[?:?]
        at com.sk89q.worldedit.extent.world.SideEffectExtent.setBlock(SideEffectExtent.java:89) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.setBlock(WatchdogTickingExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.world.SurvivalModeExtent.setBlock(SurvivalModeExtent.java:100) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.world.BlockQuirkExtent.setBlock(BlockQuirkExtent.java:63) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.world.ChunkLoadingExtent.setBlock(ChunkLoadingExtent.java:70) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.cache.LastAccessExtentCache.setBlock(LastAccessExtentCache.java:74) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
        at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:114) ~[?:?]
        at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:47) ~[?:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:269) ~[?:?]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
        at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:828) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:536) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 21 more
```

**To Reproduce**

1. make selection
2. //copy
3. move location
4. //paste

**Comment by wizjany** [comment]
please provide a full log, there's one more stacktrace missing...

**Comment by SlimeDog** [comment]
Apologies. Added the third bit.

**Comment by wizjany** [comment]
downgrade, you're using 1.16 builds of WE.

**Comment by me4502** [comment]
Yeah gonna need the full logs, that error should be impossible

**Comment by SlimeDog** [comment]
Already reverted to WE 7.2.0-SNAPSHOT+5066-849a515. Sorry for the confusion. Previous versions have been backwards-compatible.

**Comment by wizjany** [comment]
they should probably be once we have 1.16 bukkit to work with. we just can't compile on something that doesn't exist yet so we're waiting on that.

**Comment by SlimeDog** [comment]
Understood. Thanks. Suggest making that clearer in the notes, but no worries. We're all twitching at the bit. :)

**Comment by wizjany** [comment]
https://i.imgur.com/RbpKTFR.png
immediately updating to dev builds marked '1.16' is kinda on you tbh. in fact, most people would recommend not just automatically grabbing the latest build constantly even if it's not marked for a new version.

**Comment by SlimeDog** [comment]
testing...
I missed the "marked 1.16". Mea culpa.
