### ISSUE TITLE
AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.WorldNativeAccess_v1_15_R2 does not define or inherit an implementation of the resolved method 'abstract void updateNeighbors(java.lang.Object, java.lang.Object, java.lang.Object, int)' of interface com.sk89q.worldedit.internal.wna.WorldNativeAccess

### ISSUE THREAD

**Issue by mibby** [EngineHub/WorldEdit#1378]
**Versions**
WorldEdit-Bukkit dev 5076
Tuinity dev 127 (Paper Fork - Spigot 1.15.2)

**Describe the bug**
Error on copy/paste/undo operations.
https://paste.ubuntu.com/p/GQsPtHQCTr/

```
[12:03:50] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@504c3a2 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:349) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1878) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1686) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1162) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1290) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Tuinity-"98e9d5b"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 24 more
Caused by: java.lang.AbstractMethodError: Receiver class com.sk89q.worldedit.bukkit.adapter.impl.WorldNativeAccess_v1_15_R2 does not define or inherit an implementation of the resolved method 'abstract void updateNeighbors(java.lang.Object, java.lang.Object, java.lang.Object, int)' of interface com.sk89q.worldedit.internal.wna.WorldNativeAccess.
	at com.sk89q.worldedit.internal.wna.WorldNativeAccess.markAndNotifyBlock(WorldNativeAccess.java:178) ~[?:?]
	at com.sk89q.worldedit.internal.wna.WorldNativeAccess.setBlock(WorldNativeAccess.java:87) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:443) ~[?:?]
	at com.sk89q.worldedit.extent.world.SideEffectExtent.setBlock(SideEffectExtent.java:89) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.setBlock(WatchdogTickingExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.world.SurvivalModeExtent.setBlock(SurvivalModeExtent.java:98) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.world.BlockQuirkExtent.setBlock(BlockQuirkExtent.java:63) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.world.ChunkLoadingExtent.setBlock(ChunkLoadingExtent.java:70) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.cache.LastAccessExtentCache.setBlock(LastAccessExtentCache.java:74) ~[?:?]
	at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:79) ~[?:?]
	at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:114) ~[?:?]
	at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:47) ~[?:?]
	at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:269) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[?:?]
	at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[?:?]
	at com.sk89q.worldedit.EditSession.flushSession(EditSession.java:828) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:536) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 24 more
```

**Additional context**
Caused by commit https://github.com/EngineHub/WorldEdit/commit/6412383636d679af9e9235401d30e691e1dd8829?

**Comment by octylFractal** [comment]
If you could find the commit, you could probably figure out that this is not really a bug, as it says:
> Requires an update in the Bukkit Adapters later.

**Comment by octylFractal** [comment]
Also, duplicates #1375.

**Comment by mibby** [comment]
I missed the note where it said required updated Bukkit Adapters, as I read the commit changes being for Fabric. Generally WorldEdit dev builds have been backwards compatible, thus I forwarded this issue. 

Didn't catch the duplicate report since it was closed.
