### ISSUE TITLE
Potential bug? Cast problem in Custom dimensions!

### ISSUE THREAD

**Issue by Blaueschmied** [EngineHub/WorldEdit#1397]
**Versions**

WorldEdit version: 7.2.0-SNAPSHOT-dist (forge)
Platform version: Minecraft 1.16.1, Forge 1.16.1-forge-32.0.25

**Describe the bug**
when i try to use the brushes in the new custom Dimension this occures.
java.lang.ClassCastException: net.minecraft.world.storage.DerivedWorldInfo cannot be cast to net.minecraft.world.storage.ServerWorldInfo

**To Reproduce**

1. Create a world with a custom dimension in vanilla minecraft 1.16.1 (Forge has problems with reading the extra information 
    while creating new world with the datapack options)
2. load the world in Forge version 32.0.25.
3. teleport to new custom dimension.
4. Use the brush functions in the newly added custom dimensions of minecraft 1.16.1. 

**Expected behavior**

normal use of brushes in all dimensions.

**Additional context**

Stacktrace: [bug.txt](https://github.com/EngineHub/WorldEdit/files/4844168/bug.txt)

**Comment by me4502** [comment]
Please provide the entire stacktrace

**Comment by wizjany** [comment]
please fill out the issue template really....

**Comment by Blaueschmied** [comment]
[com.sk89q.worldedit.extension.platform.PlatformCommandManager/]: An unexpected error while handling a WorldEdit command
java.lang.ClassCastException: net.minecraft.world.storage.DerivedWorldInfo cannot be cast to net.minecraft.world.storage.ServerWorldInfo
	at com.sk89q.worldedit.forge.ForgeWorld.getName(ForgeWorld.java:151) ~[?:?]
	at com.sk89q.worldedit.internal.command.CommandLoggingHandler.beforeCall(CommandLoggingHandler.java:96) ~[?:?]
	at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[?:?]
	at com.sk89q.worldedit.command.BrushCommandsRegistration.cmd$sphere(BrushCommandsRegistration.java:357) ~[?:?]
	at com.sk89q.worldedit.command.BrushCommandsRegistration$$Lambda$5194/262842820.run(Unknown Source) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:491) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [?:?]
	at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:288) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_5_ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.2.0-service.jar:?]
	at net.minecraft.command.Commands.func_197059_a(Commands.java:207) [?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1042) [?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1025) [?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) [?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5944/2099664420.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:738) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:157) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:721) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:715) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:701) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:647) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4825/2032901587.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
