### ISSUE TITLE
Fabric NPE in logs

### ISSUE THREAD

**Issue by Prospector** [EngineHub/WorldEdit#1410]
**Versions**
WorldEdit version: worldedit-fabric-mc1.16.1-7.2.0-beta
Platform version: Fabric 1.16.1

```Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
... 25 more
Caused by: java.lang.NullPointerException
at com.sk89q.worldedit.fabric.FabricPlayer.getLocale(FabricPlayer.java:137) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.fabric.FabricPlayer.print(FabricPlayer.java:164) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.extension.platform.PlayerProxy.print(PlayerProxy.java:140) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.extension.platform.Actor.printError(Actor.java:95) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleUnknownException(PlatformCommandManager.java:584) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:522) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-beta-01.jar:?]
... 25 more
```
Not sure how to reproduce, it seems to just happen at times. No crash, just lots of log spam.

**Comment by me4502** [comment]
This happens when a client hasn't told the server what language to use. It's worked around in later versions of WorldEdit. Update if you want it to go away.

**Comment by Prospector** [comment]
Hmm, this is the latest on CurseForge atm.
