### ISSUE TITLE
Please Report This error log

### ISSUE THREAD

**Issue by Mineinjava** [EngineHub/WorldEdit#1428]
**Versions**

WorldEdit version:

```
[11:58:27 INFO]: WorldEdit version (unknown)
[11:58:27 INFO]: https://github.com/EngineHub/WorldEdit/
[11:58:27 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.1.0;8e55131)

[11:58:27 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```
Platform version:

 `This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Describe the bug**

not really a bug, just an error

**To Reproduce**

run //drain 200 from server console

**Expected behavior**

nothing, I am reporting this error because it said to.

**Screenshots**

**Additional context**

```
[11:57:20 INFO]: Please report this error: [See console]
[11:57:20 INFO]: java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
[11:57:20 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.UnsupportedOperationException: Chunk batching not supported by this session.
        at com.sk89q.worldedit.EditSession.setBatchingChunks(EditSession.java:532) ~[?:?]
        at com.sk89q.worldedit.EditSession.enableStandardMode(EditSession.java:303) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:242) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:294) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.extract$editSession(UtilityCommandsRegistration.java:650) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$_drain(UtilityCommandsRegistration.java:434) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:348) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Mineinjava** [comment]
this is probraby not an issue, but the error said to report it.
