### ISSUE TITLE
//pos1, //hpos1 exception error

### ISSUE THREAD

**Issue by ShimajiroOTS** [EngineHub/WorldEdit#1434]
Note: I am not good at English! We will respond by Google translation.

**Versions**

WorldEdit version: worldedit-fabric-mc1.16.1-7.2.0(Build: #5153-373f869)
Platform version: 1.16.1 + Fabric loader 0.8.9 Build 203 + Fabric API Build 372

**Describe the bug**

Under Japanese environment, if you use //pos1, //hpos1 command, it will look like the image below.
Also, even if you left-click with the ax, the blocks will not be restored.
Since the selection and copy are done correctly, it is possible that the language file has some kind of bug.

**To Reproduce**

1. Change the language to Japanese.
2. Run the //pos1 or //hpos1 command.
3. "Java.lang.IllegalArgumentException: Unmatched braces in the pattern." is displayed in the chat field.

**Expected behavior**

As mentioned above, there is a possibility that something is wrong with the language file, so please check it.

**Screenshots**

![2020-07-11_23 55 35](https://user-images.githubusercontent.com/68157163/87227465-128efd80-c3d6-11ea-8655-cfc8cbd0a9cb.png)

**Bug Report (Part)**
[23:50:41] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.BlockInteractEvent@d61b41e to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.WorldEdit.handleBlockLeftClick(WorldEdit.java:663) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit.onLeftClickBlock(FabricWorldEdit.java:231) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit$$Lambda$2212/542597941.interact(Unknown Source) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackBlockCallback.lambda$null$0(AttackBlockCallback.java:44) [c4c67e1d-c2b8-496d-ba93-67131314a19a.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackBlockCallback$$Lambda$2187/2117651770.interact(Unknown Source) [c4c67e1d-c2b8-496d-ba93-67131314a19a.jar:?]
	at net.minecraft.class_3225.handler$zbi000$startBlockBreak(class_3225.java:554) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:944) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600$$Lambda$5364/628938805.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:150) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4646/1557189547.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	... 28 more
Caused by: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508) ~[?:1.8.0_51]
	at java.text.MessageFormat.<init>(MessageFormat.java:380) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.translation.TranslationManager.lambda$new$0(TranslationManager.java:84) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager$$Lambda$6292/2132626823.apply(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer$1.translation(TranslatableComponentRenderer.java:57) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderTranslatable(TranslatableComponentRenderer.java:118) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:50) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:188) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricPlayer.print(FabricPlayer.java:169) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlayerProxy.print(PlayerProxy.java:143) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.Actor.printInfo(Actor.java:104) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.explainPrimarySelection(CuboidRegionSelector.java:159) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.tool.SelectionWand.actSecondary(SelectionWand.java:43) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:342) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	... 28 more
[23:50:41] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.BlockInteractEvent@34466df4 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.WorldEdit.handleBlockLeftClick(WorldEdit.java:663) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit.onLeftClickBlock(FabricWorldEdit.java:231) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit$$Lambda$2212/542597941.interact(Unknown Source) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackBlockCallback.lambda$null$0(AttackBlockCallback.java:44) [c4c67e1d-c2b8-496d-ba93-67131314a19a.jar:?]
	at net.fabricmc.fabric.api.event.player.AttackBlockCallback$$Lambda$2187/2117651770.interact(Unknown Source) [c4c67e1d-c2b8-496d-ba93-67131314a19a.jar:?]
	at net.minecraft.class_3225.handler$zbi000$startBlockBreak(class_3225.java:554) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:944) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600$$Lambda$5364/628938805.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:150) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4646/1557189547.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	... 28 more
Caused by: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508) ~[?:1.8.0_51]
	at java.text.MessageFormat.<init>(MessageFormat.java:380) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.translation.TranslationManager.lambda$new$0(TranslationManager.java:84) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager$$Lambda$6292/2132626823.apply(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer$1.translation(TranslatableComponentRenderer.java:57) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderTranslatable(TranslatableComponentRenderer.java:118) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:50) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:188) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricPlayer.print(FabricPlayer.java:169) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlayerProxy.print(PlayerProxy.java:143) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.Actor.printInfo(Actor.java:104) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.explainPrimarySelection(CuboidRegionSelector.java:159) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.tool.SelectionWand.actSecondary(SelectionWand.java:43) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:342) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	... 28 more
[23:55:34] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508) ~[?:1.8.0_51]
	at java.text.MessageFormat.<init>(MessageFormat.java:380) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.translation.TranslationManager.lambda$new$0(TranslationManager.java:84) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager$$Lambda$6292/2132626823.apply(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer$1.translation(TranslatableComponentRenderer.java:57) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.TranslatableComponentRenderer.renderTranslatable(TranslatableComponentRenderer.java:118) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:50) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.translation.TranslationManager.convertText(TranslationManager.java:188) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.formatting.WorldEditText.format(WorldEditText.java:38) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricPlayer.print(FabricPlayer.java:169) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlayerProxy.print(PlayerProxy.java:143) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.Actor.printInfo(Actor.java:104) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.explainPrimarySelection(CuboidRegionSelector.java:159) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.SelectionCommands.pos1(SelectionCommands.java:132) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.SelectionCommandsRegistration.cmd$_pos1(SelectionCommandsRegistration.java:326) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.SelectionCommandsRegistration$$Lambda$4155/401044800.run(Unknown Source) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:491) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:64) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.CommandWrapper$$Lambda$5119/712566451.run(Unknown Source) [worldedit-fabric-mc1.16.1-7.2.0-SNAPSHOT-dist.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) [brigadier-1.0.17.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) [brigadier-1.0.17.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:260) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1134) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1121) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:36) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:9) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_2600$$Lambda$5364/628938805.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:172) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:134) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:150) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4646/1557189547.run(Unknown Source) [intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]

**Additional context**

There may be duplicates, but there was a possibility of a bug unique to the Japanese environment, so we have posted.

**Comment by wizjany** [comment]
There was a typo in the translation string: https://crowdin.com/translate/worldedit-core/4/en-ja#800
I've corrected it manually for now. Wonder if it's worth making a check for this sort of thing to prevent errors like this making it into builds.

**Comment by ShimajiroOTS** [comment]
I want to build it with 1.16 soon.
This bug has a slight impact on construction.

**Comment by wizjany** [comment]
should no longer happen as of 3a3686289fb44d2fd5abedf8fe3a6d339e672d0f
