### ISSUE TITLE
//regen giving java.lang.IllegalStateException: Regen failed error on All The Mods 6 modpack 1.16.4

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [EngineHub/WorldEdit#1613]
Versions

WorldEdit version: 7.2.1 
Platform version: 1.16.4

Describe the bug:
regen not work :(

To Reproduce:
install worldedit to all the mods 6 modpack from curseforge latest version for both modpack and the worldedit mod for 1.16.4 itself
...
...
Expected behavior: regen work

Screenshots: its just an error

Additional context: possible mod confliction?

```
java.lang.IllegalStateException: Regen failed
	at com.sk89q.worldedit.forge.ForgeWorld.regenerate(ForgeWorld.java:323) ~[worldedit:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[worldedit:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit:?]
	at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:290) ~[worldedit:?]
	at net.minecraftforge.eventbus.ASMEventHandler_104_ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraft.command.Commands.func_197059_a(Commands.java:211) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1119) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1102) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1081) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.IllegalStateException: Unable to map GeneratorOptions: Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Value 10 outside of range [0:7]; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Value 10 outside of range [0:7]; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992; Unknown registry element ChunkCornerPlacement@3e20e5c2; Unknown registry element vazkii.quark.base.world.DeferedFeature@21e0e903; Unknown registry element ChunkCornerPlacement@cdc8f6d; Unknown registry element vazkii.quark.base.world.DeferedFeature@727fa456; Unknown registry element ChunkCornerPlacement@2f66173a; Unknown registry element vazkii.quark.base.world.DeferedFeature@2e5fe93; Unknown registry element ChunkCornerPlacement@3699089c; Unknown registry element vazkii.quark.base.world.DeferedFeature@42d3e2f2; Unknown registry element ChunkCornerPlacement@3313d7b2; Unknown registry element vazkii.quark.base.world.DeferedFeature@488f88f4; Unknown registry element ChunkCornerPlacement@1c5d1c68; Unknown registry element vazkii.quark.base.world.DeferedFeature@75a09230; Unknown registry element ChunkCornerPlacement@3b6811f6; Unknown registry element vazkii.quark.base.world.DeferedFeature@10aa186; Unknown registry element ChunkCornerPlacement@5737c468; Unknown registry element vazkii.quark.base.world.DeferedFeature@7057ca29; Unknown registry element ChunkCornerPlacement@73593029; Unknown registry element vazkii.quark.base.world.DeferedFeature@29cfe48c; Unknown registry element ChunkCornerPlacement@5e7f270c; Unknown registry element vazkii.quark.base.world.DeferedFeature@8416992
	at com.sk89q.worldedit.forge.ForgeWorld.lambda$doRegen$2(ForgeWorld.java:355) ~[worldedit:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?]
	at com.sk89q.worldedit.forge.ForgeWorld.doRegen(ForgeWorld.java:352) ~[worldedit:?]
	at com.sk89q.worldedit.forge.ForgeWorld.regenerate(ForgeWorld.java:321) ~[worldedit:?]
	... 36 more

```

**Comment by AdovinOFFICIAL** [comment]
bump?

**Comment by octylFractal** [comment]
Yes, it's a mod conflict, no I don't think we're likely to fix it. Regen is very hacky and it is super easy for it to conflict.

**Comment by Rubyz67** [comment]
same with me

**Comment by octylFractal** [comment]
This is probably effectively fixed in newer versions.
