### ISSUE TITLE
Bug With Datapack

### ISSUE THREAD

**Issue by DoctaEnkoda** [EngineHub/WorldEdit#1664]
**Versions**
WorldEdit version: 7.2.2
Platform version: Paper

**Describe the bug**
`9:39:50 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Biome.name()" because "biome" is null
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:370) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBiome(BukkitWorld.java:517) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommands.biomeInfo(BiomeCommands.java:140) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$biomeinfo(BiomeCommandsRegistration.java:156) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:375) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]`

**To Reproduce**
Use datapack add Biome (1.16) and execute command : /biomeinfo

**Suggest : **
Add compatibility with Custom Biome Datapack

**Comment by octylFractal** [comment]
Not really ours to do, it's on Bukkit to have the API for it. Might be able to special-case Paper if they add some API for it.

**Comment by octylFractal** [comment]
And actually, upon searching, this duplicates #1538.

**Comment by IllagerCaptain** [comment]
@octylFractal yes I'm a year and a half late, but this is about `/biomeinfo` not working correctly with custom biomes, and #1538 is about `//setbiome` not working correctly with custom biomes. I don't think this is a duplicate, but it has the same cause.

**Comment by wizjany** [comment]
we disagree. please don't necrobump issues.

**Comment by octylFractal** [comment]
Same cause == duplicate
