### ISSUE TITLE
Schematic Load Error

### ISSUE THREAD

**Issue by GeoBrick** [EngineHub/WorldEdit#1687]
When i try to load a schematic that previously worked in the same version of minecraft it doesnt work and says Check the contol panel.  I check the logs and it shows this :

20:13:49] [Server thread/INFO]: GeoBrick issued server command: /schem load wpfd1
[20:13:49] [WorldEdit Task Executor - 0/ERROR]: Uncaught exception occurred in task: Loading schematic wpfd1
java.lang.ClassCastException: com.sk89q.jnbt.CompoundTag cannot be cast to com.sk89q.worldedit.util.nbt.CompoundBinaryTag
	at com.sk89q.worldedit.bukkit.adapter.impl.DataConverters_1_16_R3.fixUp(DataConverters_1_16_R3.java:74) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:250) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:124) ~[?:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:362) ~[?:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:344) ~[?:?]
	at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[server.jar:git-Paper-"b89788a"]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[server.jar:git-Paper-"b89788a"]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[server.jar:git-Paper-"b89788a"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by wizjany** [comment]
probably outdated, missing template
