### ISSUE TITLE
//regen IllegalStateException after leaving and rejoining world 

### ISSUE THREAD

**Issue by helpimnotdrowning** [EngineHub/WorldEdit#1752]
### WorldEdit Version

7.2.5

### Platform Version

Fabric-Official(7.2.5+57d5ac9)

### Bug Description

//regen fails with IllegalStateException after leaving and rejoining world.

### Expected Behavior

not do that

### Reproduction Steps

1. Join world
2. Use //regen (haven't tested not doing this)
3. Leave
4. Rejoin (any) world
5. Use //regen

### Anything Else?

```
[18:16:12] [main/INFO]: [CHAT] java.lang.IllegalStateException: Regen failed
[18:16:12] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: Regen failed
	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47) ~[?:?]
	at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:317) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit-mod-7.2.5-dist.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[worldedit-mod-7.2.5-dist.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:64) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?]
	at net.minecraft.server.command.CommandManager.redirect$zfo000$performCommand(CommandManager:549) ~[?:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager:249) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1211) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.method_31286(ServerPlayNetworkHandler:1198) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onGameMessage(ServerPlayNetworkHandler:1177) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:36) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:9) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:761) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:155) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer:743) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:737) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer:722) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bmk000$modifiedRunLoop(MinecraftServer:5319) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Unable to map GeneratorOptions: Unknown tag: net.minecraft.class_5394@631b7659; Unknown tag: net.minecraft.class_5394@631b7659; Unknown tag: net.minecraft.class_5394@631b7659; Unknown tag: net.minecraft.class_5394@631b7659; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1; Unknown tag: net.minecraft.class_5394@36b96ce1
	at com.sk89q.worldedit.fabric.FabricWorld.lambda$doRegen$2(FabricWorld.java:349) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-4.0.26.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorld.doRegen(FabricWorld.java:346) ~[worldedit-mod-7.2.5-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:315) ~[worldedit-mod-7.2.5-dist.jar:?]
	... 35 more
```

**Comment by octylFractal** [comment]
Do you have any other mods? This should generally work out fine otherwise, I don't know why closing and re-opening a world would cause this, and it didn't for me.

**Comment by Greg-J** [comment]
I get the following when trying to use //regen on Fabric:

```Jul 07 15:45:52 dekocraft2 java[11042]: [15:45:52] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
Jul 07 15:45:52 dekocraft2 java[11042]: java.lang.IllegalStateException: Regen failed
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:317) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:64) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_3244.method_14370(class_3244.java:1239) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_3244.method_31286(class_3244.java:1223) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_3244.method_12048(class_3244.java:1206) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.handler$zoh000$modifiedRunLoop(MinecraftServer.java:5402) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at java.lang.Thread.run(Thread.java:831) [?:?]
Jul 07 15:45:52 dekocraft2 java[11042]: Caused by: java.lang.IllegalStateException: Unable to map GeneratorOptions: Missing value [0] : ResourceKey[minecraft:worldgen/configured_structure_feature / more_structures:bastion_remnant_soul_sand_valley]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.fabric.FabricWorld.lambda$doRegen$2(FabricWorld.java:349) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[intermediary-server.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.fabric.FabricWorld.doRegen(FabricWorld.java:346) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:315) ~[worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar:?]
Jul 07 15:45:52 dekocraft2 java[11042]:         ... 36 more```

**Comment by TheNety** [comment]
I get the same error on Purpur 1.17.1. No rejoin needed, just anytime we tried it failed. https://mcpaste.io/64234449c20c1772

**Comment by wizjany** [comment]
entirely unrelated.

**Comment by TianLuoRain** [comment]
I have the same problem.
I moved my 1.12.2 save to 1.16.5 game. Now I cannot use the //regen anymore.
I tried it on a native 1.16.5 save and it worked fine.
So I believe the reason is that I changed the game's version.
I want a instructions about why. I guess it has something to do with saves, versions, seeds, etc., but I don't know how to solve it.
