### ISSUE TITLE
worldedit not working on 1.17 spigot

### ISSUE THREAD

**Issue by Pindang2** [EngineHub/WorldEdit#1789]
### WorldEdit Version

7.2.6-SNAPSHOT

### Platform Version

3147-Spigot-9472b09-d7ef1e9 1.17-R0.1-SNAPSHOT

### Bug Description

I testing Worldedit 1.17 test builds on 1.17 spigot snapshot.
wood axe wand working, but when I set two positions, and set, worldedit does not worked with following errors:

[10:47:22 INFO]: Pindang2 issued server command: //set acacia_wood
[10:47:22 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: Currently invalid
	at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:120) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:101) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
	at java.lang.Thread.run(Thread.java:831) [?:?]
	Suppressed: java.lang.IllegalStateException: Currently invalid
		at com.sk89q.worldedit.util.lifecycle.Lifecycled.lambda$valueOrThrow$0(Lifecycled.java:99) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
		at com.sk89q.worldedit.util.lifecycle.Lifecycled.valueOrThrow(Lifecycled.java:99) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.bukkit.BukkitServerInterface.getWatchdog(BukkitServerInterface.java:128) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:120) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:93) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
		at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:?]
		at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
		at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
		at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
		at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
		at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
		at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar:7.2.6-SNAPSHOT]
		at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.TickTask.run(SourceFile:18) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[1.17.server.jar:3147-Spigot-9472b09-d7ef1e9]
		at java.lang.Thread.run(Thread.java:831) [?:?]

### Expected Behavior

![image](https://user-images.githubusercontent.com/45694028/122318903-cd1a6f00-cf5a-11eb-90a7-edb221416044.png)

### Reproduction Steps

1. //wand
2. set pos1, pos2 with wooden axe wand (working)
3. //set stone

### Anything Else?

I'm using Y-extended world using Mojang preview datapack.
but same error occurred to regular world.

**Comment by wizjany** [comment]
update
