### ISSUE TITLE
Zip file Closed

### ISSUE THREAD

**Issue by Heppy-Prog** [EngineHub/WorldEdit#1820]
### WorldEdit Version

7.2.6 Beta

### Platform Version

Paper 1.17.1

### Bug Description

as soon as I restart the server, I get the following error message on exit, as long as World Edit is in the plugin directory.
 
>....[15:05:22 ERROR]: Caught previously unhandled exception :
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapCommandSender(WorldEditPlugin.java:478) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitCommandInspector.lambda$testPermission$0(BukkitCommandInspector.java:80) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
	at com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:46) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:100) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:48) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:20) ~[patched_1.17.1.jar:git-Paper-90]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.17.1.jar:git-Paper-90]
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[patched_1.17.1.jar:git-Paper-90]
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[patched_1.17.1.jar:git-Paper-90]
	at io.papermc.paper.console.BrigadierCommandHighlighter.highlight(BrigadierCommandHighlighter.java:28) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:3818) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3800) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3700) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3636) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:629) ~[patched_1.17.1.jar:git-Paper-90]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:113) ~[patched_1.17.1.jar:git-Paper-90]

### Expected Behavior

no error xD by restart the server

### Reproduction Steps

install paper 1.17.1 -> start server
if  its run -> stop server
put World Edit in Plugin folder
start server
if its run -> restart server
error

**Comment by wizjany** [comment]
generally means classloader issues (including /reload), jar file getting messed with during runtime (such as replacing the jar without restarting), etc.
not a WE issue in any case.
