### ISSUE TITLE
[1.17.1 Spigot] WorldEdit crash when running commands (//expand for example)

### ISSUE THREAD

**Issue by Pocketkid2** [EngineHub/WorldEdit#1831]
### WorldEdit Version

7.2.6-SNAPSHOT+5866-954210d

### Platform Version

3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1)

### Bug Description

I select a block with the WorldEdit want, but when I type //expand 10 or //expand 10 north, I get this console error:

  ```
[15:07:45] [Server thread/INFO]: Pocketkid2 issued server command: //expand 10
  [15:07:45] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@145b181e to handler EventHandler{priority=NORMAL}
  java.lang.reflect.InvocationTargetException: null
	  at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	  at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:107) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	  at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:71) ~[?:?]
	  at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:519) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	  at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
	  at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1133) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1110) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1039) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3180-Spigot-38e6c03-ca0fe5b]
	  at java.lang.Thread.run(Thread.java:831) [?:?]
  Caused by: java.lang.reflect.InvocationTargetException
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	  at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	  ... 28 more
  Caused by: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until WorldEdit is initialized.
	  at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:170) ~[?:?]
	  at com.sk89q.worldedit.extension.platform.PlatformManager.createProxyActor(PlatformManager.java:264) ~[?:?]
	  at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:470) ~[?:?]
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	  at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	  at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	  ... 28 more

```

### Expected Behavior

I expected the command to behave normally

### Reproduction Steps

See bug description above. On the latest version of spigot/bukkit and WorledEdit 7.2.6 dev build, not all of the commands seem to work correctly.

**Comment by wizjany** [comment]
we don't support plugins that modify WE.

**Comment by Pocketkid2** [comment]
@wizjany Are you referring to AsyncWorldEdit?
