### ISSUE TITLE
//setbiome error

### ISSUE THREAD

**Issue by DenaryDev** [EngineHub/WorldEdit#1840]
### WorldEdit Version

7.2.6-SNAPSHOT+5872-9c7f454

### Platform Version

git-Paper-104 (MC: 1.17.1)

### Bug Description

When I try to change the biome, this error appears:

`[20:49:42 INFO]: DenaryDev issued server command: //setbiome mushroom_fields
[20:49:42 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.1.jar:git-Paper-107]
at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:518) ~[patched_1.17.1.jar:git-Paper-107]
at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getBiome(CraftWorld.java:1118) ~[patched_1.17.1.jar:git-Paper-107]
at com.sk89q.worldedit.bukkit.BukkitWorld.getBiome(BukkitWorld.java:540) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getBiome(WatchdogTickingExtent.java:114) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getBiome(WatchdogTickingExtent.java:114) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.getBiome(AbstractDelegateExtent.java:104) ~[?:?]
at com.sk89q.worldedit.extent.ChangeSetExtent.setBiome(ChangeSetExtent.java:71) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
at com.sk89q.worldedit.EditSession.setBiome(EditSession.java:676) ~[?:?]
at com.sk89q.worldedit.function.biome.BiomeReplace.apply(BiomeReplace.java:66) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
at com.sk89q.worldedit.command.BiomeCommands.setBiome(BiomeCommands.java:181) ~[?:?]
at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$_setbiome(BiomeCommandsRegistration.java:171) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-107]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2180) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1991) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1972) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-107]
at java.lang.Thread.run(Thread.java:831) [?:?]`

### Expected Behavior

Changing the biome in the selected area

### Reproduction Steps

1. Select pos1 and pos2
2. Run //setbiome <any biome>

**Comment by octylFractal** [comment]
This is an error in Spigot/Paper, report to them.

**Comment by MinecraftFabricEnjoyer** [comment]
I had a same problem but in singleplayer

**Comment by wizjany** [comment]
literally impossible since that error is specifically in craftbukkit code. if you have a *different* issue with setbiome, that's not the same problem and doesn't belong in this issue.

**Comment by octylFractal** [comment]
This has pretty much been fixed AFAIK.
