### ISSUE TITLE
//regen dont work

### ISSUE THREAD

**Issue by DoctaEnkoda** [EngineHub/WorldEdit#1842]
### WorldEdit Version

Bukkit-Official(7.2.6-SNAPSHOT+5883-cfd2098)

### Platform Version

 git-Purpur-"2721192" (MC: 1.17.1)

### Bug Description

I have an error :
```
[18:51:32] [Server thread/INFO]: DoctaEnkoda issued server command: //chunk
[18:51:34] [Server thread/INFO]: DoctaEnkoda issued server command: //regen
[18:51:34] [Server thread/WARN]: Regeneration via adapter failed.
java.lang.IllegalStateException: Regen failed.
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:580) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:216) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2319) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2130) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2111) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[Purpur-Server-reobf.jar:git-Purpur-"2721192"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: Unable to map GeneratorOptions
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.lambda$doRegen$5(Spigot_v1_17_R1_2.java:614) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.doRegen(Spigot_v1_17_R1_2.java:614) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:578) ~[?:?]
	... 36 more
```
	 
I use Purpur 1.17.1

### Expected Behavior

A regeneration of chunk.

### Reproduction Steps

1. Create World with datapack
2. //chunk
3. //regen

**Comment by DoctaEnkoda** [comment]
Why Invalid ?

**Comment by wizjany** [comment]
duplicate
