### ISSUE TITLE
//wand not working or any other command of world edit

### ISSUE THREAD

**Issue by ZayanPlayz** [EngineHub/WorldEdit#1844]
### WorldEdit Version

WorldEdit 7.2.6 Beta 1 (1.13.2 - 1.17.1)

### Platform Version

PaperMC 1.17.1

### Bug Description

whenever I do //wand or any other command of world edit, this error log comes up

### Expected Behavior

This only works when I restart or start my server, after 10 or 15min it stops working

### Reproduction Steps

1. //wand
2. not working

### Anything Else?

here is the error log

[18:19:12 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[minecraft_server.jar:git-Paper-112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[minecraft_server.jar:git-Paper-112]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235) ~[minecraft_server.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:121) ~[minecraft_server.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[minecraft_server.jar:git-Paper-112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:?]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:?]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:?]
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:440) ~[?:?]
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:242) ~[?:?]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121) ~[?:?]
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73) ~[?:?]
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:621) ~[?:?]
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:619) ~[?:?]
	at java.lang.reflect.Executable.getAnnotation(Executable.java:587) ~[?:?]
	at java.lang.reflect.Method.getAnnotation(Method.java:696) ~[?:?]
	at com.sk89q.worldedit.internal.command.CommandLoggingHandler.beforeCall(CommandLoggingHandler.java:67) ~[?:?]
	at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[?:?]
	at com.sk89q.worldedit.command.SelectionCommandsRegistration.cmd$_wand(SelectionCommandsRegistration.java:402) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[minecraft_server.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[minecraft_server.jar:git-Paper-112]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[minecraft_server.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by octylFractal** [comment]
Likely either reload, plugman, or another plugin is interfering with normal classloading. Please try without those, and if it continues to break come to the Discord for support.
