### ISSUE TITLE
Exception with MC/Forge 1.17.1

### ISSUE THREAD

**Issue by nelgin** [EngineHub/WorldEdit#1859]
### WorldEdit Version

7.2.6-beta-02

### Platform Version

Forge 1.17.1

### Bug Description

When using the forge ./run.sh command I get the following exception:

$ ./run.sh
[08:19:31] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 37.0.18, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[08:19:31] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.1 by Private Build
Exception in thread "main" java.lang.module.ResolutionException: Module worldedit contains package javax.annotation.meta, module server.extra exports package javax.annotation.meta to worldedit
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:743)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.16/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:89)

### Expected Behavior

I would expect minecraft to run.

### Reproduction Steps

I copied the following files and directories from server-1.16.5 to server-1.17.1

*.json config defaultconfigs eula.txt server.properties world

Then I downloaded the minecraft 1.17.1 .jar file
Then downloaded the forge installer and ran it with the --installServer option.

I started minecraft and it came up ok.

After shutting down minecraft I created a mods directory and placed the WorldEdit .jar file there.

Now when I start minecraft I get the reported error.

### Anything Else?

Same thing happens if I create a brand new directory with everything as defaults.

**Comment by octylFractal** [comment]
Fixed by 96c97997dc10f1a8626643dea66243f9783670f3.
