### ISSUE TITLE
1.17.1 forge sserver

### ISSUE THREAD

**Issue by boxermiku** [EngineHub/WorldEdit#1864]
### WorldEdit Version

7.2.6-beta2

### Platform Version

forge-1.17.1-37.0.22

### Bug Description

無法在伺服器執行!!

### Expected Behavior

無法在伺服器執行!!

### Reproduction Steps

A:\One**** - Tang.****\創世神插件伺服器\1.17.1 forge server>REM Forge requires a configured set of both JVM and program arguments.

A:\One**** - Tang.****\創世神插件伺服器\1.17.1 forge server>REM Add custom JVM arguments to the user_jvm_args.txt

A:\One**** - Tang.****\創世神插件伺服器\1.17.1 forge server>REM Add custom program arguments {such as nogui} to this file at the end of the next line

A:\One**** - Tang.****\創世神插件伺服器\1.17.1 forge server>java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.17.1-37.0.22/win_args.txt
2021-08-04 08:30:04,827 main WARN Advanced terminal features are not available in this environment
[08:30:05] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 37.0.22, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[08:30:05] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.2 by Oracle Corporation
Exception in thread "main" java.lang.module.ResolutionException: Modules worldedit and server.extra export package javax.annotation.concurrent to module elevatorid
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:822)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:743)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.16/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:89)

A:\One**** - Tang.****\創世神插件伺服器\1.17.1 forge server>pause
請按任意鍵繼續 . . .

**Comment by wizjany** [comment]
already fixed, need to use a dev build
