### ISSUE TITLE
Cannot use the WorldEdit plugin, using any of the commands will report an error

### ISSUE THREAD

**Issue by yixiaip** [EngineHub/WorldEdit#1869]
### WorldEdit Version

Bukkit-official(7.2.5+57d5ac9)

### Platform Version

arclight-forge-1.16.5

### Bug Description

The following is one of the errors reported using the command

`[c.s.w.e.p.PlatformCommandManager/]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.lang.Throwable.addSuppressed(Throwable.java:1072) ~[?:?] {}
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:104) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.bukkit.BukkitAdapter.lambda$adapt$4(BukkitAdapter.java:462) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.bukkit.fastutil.ints.Int2ObjectOpenHashMap.computeIfAbsent(Int2ObjectOpenHashMap.java:479) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:456) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:681) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.function.mask.ExistingBlockMask.test(ExistingBlockMask.java:44) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.function.GroundFunction.isGround(GroundFunction.java:80) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.function.visitor.LayerVisitor.resume(LayerVisitor.java:99) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.EditSession.makeForest(EditSession.java:2127) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.command.RegionCommands.forest(RegionCommands.java:539) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_forest(RegionCommandsRegistration.java:619) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:494) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:375) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:classloading,re:mixin}
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.20-368b0cb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A,re:mixin}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2544) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CChatMessagePacketMixin,pl:mixin:A}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.play.client.CChatMessagePacketMixin,pl:mixin:A}
	at net.minecraft.network.PacketThreadUtil.md0786af$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1903) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}
Caused by: java.lang.NullPointerException
`

### Expected Behavior

After entering the command, and executing it.

### Reproduction Steps

1.Enter://forest birch 20
2. Then it reported an error

**Comment by octylFractal** [comment]
Hybrids are unsupported.

**Comment by yixiaip** [comment]
> 不支持混合。
什么叫不支持混合，是指服务端核心吗

**Comment by octylFractal** [comment]
Bukkit and Forge together is known as a hybrid server. It is unsupported.

**Comment by yixiaip** [comment]
> Bukkit 和 Forge 一起被称为混合服务器。它不受支持。



> Bukkit 和 Forge 一起被称为混合服务器。它不受支持。

这太可惜了，还有其他办法吗？

**Comment by octylFractal** [comment]
Just use one of them. Or get the developer of "arc light" to fix the problems.
