### ISSUE TITLE
My server won't start

### ISSUE THREAD

**Issue by Computerking115** [EngineHub/WorldEdit#1870]
### WorldEdit Version

WorldEdit 7.2.6 Beta 2 (Forge/Fabric for MC 1.17.1)

### Platform Version

Forge 1.17.1 - 37.0.33 server

### Bug Description

Every time i put in the mod into the server mods folder i start up the server and it comes up with this

2021-08-14 12:44:56,775 main WARN Advanced terminal features are not available in this environment
[12:44:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 37.0.32, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[12:44:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.2 by Oracle Corporation
Exception in thread "main" java.lang.module.ResolutionException: Modules worldedit and server.extra export package javax.annotation.meta to module minecraft
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:822)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:743)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

Please see if you can fix this or at least tell me what is wrong if it is not your mod

### Expected Behavior

I expected the game to run

### Reproduction Steps

1. try fix the isue
2. if you can't then dm me on discord Computer_king115#2576

**Comment by wizjany** [comment]
#1859
