### ISSUE TITLE
`//regen` command results in console error, command failure.

### ISSUE THREAD

**Issue by ASchneider-GitHub** [EngineHub/WorldEdit#1872]
### WorldEdit Version

Bukkit-Official(7.2.6-SNAPSHOT+5908-9de6b87)

### Platform Version

CraftBukkit version 3219-Spigot-b166a49-8c6d60c

### Bug Description

Running the command `//regen` after selecting a region results in the console error below:

```
[16.08 13:37:41] [Server] [Server thread/INFO]: Doobliheim issued server command: //regen
[16.08 13:37:41] [Server] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
[16.08 13:37:41] [Server] java.lang.NoSuchMethodError'void net.minecraft.server.level.WorldServer.<init>(net.minecraft.server.MinecraftServer, java.util.concurrent.Executor, net.minecraft.world.level.storage.Convertable$ConversionSession, net.minecraft.world.level.storage.IWorldDataServer, net.minecraft.resources.ResourceKey, net.minecraft.world.level.dimension.DimensionManager, net.minecraft.server.level.progress.WorldLoadListener, net.minecraft.world.level.chunk.ChunkGenerator, boolean, long, java.util.List, boolean, org.bukkit.World$Environment, org.bukkit.generator.ChunkGenerator)'
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.doRegen(Spigot_v1_17_R1_2.java:625) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:578) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:216) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[?:?]
[16.08 13:37:41] [Server] 	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
[16.08 13:37:41] [Server] 	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
[16.08 13:37:41] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:776) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
[16.08 13:37:41] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Expected Behavior

Terrain should be regenerated according to the world seed.

### Reproduction Steps

1. Install version `Bukkit-Official(7.2.6-SNAPSHOT+5908-9de6b87)` of WorldEdit
2. Select a region in-game with the wand
3. Execute `//regen`
4. See console error

**Comment by wizjany** [comment]
spigot just completely overhauled the worldgen stuff non-compatibly so we'll have to figure out how to support both at some point ig

**Comment by wizjany** [comment]
change is now in https://github.com/EngineHub/WorldEdit/commit/1173385ac7be5c85debdf91042b89ae9b4f8f7cf

**Comment by GroGaloraGran** [comment]
Hey
maybe there is news to fix this problem?
thanks

**Comment by JOO200** [comment]
use a dev build from the build server
