### ISSUE TITLE
CLI can't open schematic

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#1892]
### WorldEdit Version

WorldEdit version 7.2.7-SNAPSHOT+5932-6c08b68 and WorldEdit CLI (version 7.2.7-SNAPSHOT) 

### Platform Version

git-Paper-251 (MC: 1.17.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I try to use a schematic and the following exception occurs:
```
java -jar worldedit-cli-7.2.7-SNAPSHOT-dist.jar
[10:39:50] [main/INFO]: WorldEdit CLI (version 7.2.7-SNAPSHOT) is loaded
[10:40:03] [main/INFO]: Loading 'C:\1.17.1\plugins\WorldEdit\schematics\test.schem'...
[10:40:03] [main/INFO]: Got request to register class com.sk89q.worldedit.cli.CLIPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@726a17c4]
[10:40:03] [main/INFO]: Registering commands with com.sk89q.worldedit.cli.CLIPlatform
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
        at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:67)
        at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:62)
        at com.google.common.io.Resources.asByteSource(Resources.java:56)
        at com.google.common.io.Resources.asCharSource(Resources.java:87)
        at com.google.common.io.Resources.toString(Resources.java:111)
        at com.sk89q.worldedit.cli.data.FileRegistries.loadDataFiles(FileRegistries.java:51)
        at com.sk89q.worldedit.cli.CLIWorldEdit.setupPlatform(CLIWorldEdit.java:103)
        at com.sk89q.worldedit.cli.CLIWorldEdit.onStarted(CLIWorldEdit.java:194)
        at com.sk89q.worldedit.cli.CLIWorldEdit.main(CLIWorldEdit.java:331)
[10:40:03] [main/INFO]: Unregistering com.sk89q.worldedit.cli.CLIPlatform from WorldEdit
```

### Expected Behavior

Use the schematic without error

### Reproduction Steps

1. Save a schematic ingame
2. Try to use it with cli

**Comment by me4502** [comment]
I don't believe CLI currently supports 1.17, as it requires a restructuring of data files due to MC stuff

**Comment by josephjthomas** [comment]
Not stale, not fixed yet

**Comment by me4502** [comment]
This was fixed a fair while ago
