### ISSUE TITLE
//regen not in overworld fails

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1923]
### WorldEdit Version

7.2.7

### Platform Version

All Platforms

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Non-overworld worlds get different level properties, so our mixins/casts won't work.

<details><summary>Stacktrace</summary>

```
java.lang.IllegalStateException: Regen failed
	at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:312) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:431) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:576) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:64) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1222) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1206) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1189) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_27 cannot be cast to class com.sk89q.worldedit.fabric.mixin.AccessorLevelProperties (net.minecraft.class_27 and com.sk89q.worldedit.fabric.mixin.AccessorLevelProperties are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at com.sk89q.worldedit.fabric.FabricWorld.doRegen(FabricWorld.java:324) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorld.regenerate(FabricWorld.java:310) ~[worldedit-fabric-mc1.17.1-7.2.8-SNAPSHOT-dist.jar:?]
	... 31 more
```
</details>

### Expected Behavior

//regen should work everywhere

### Reproduction Steps

1. Go to not-overworld (nether, end)
2. //regen

**Comment by brickmonster** [comment]
I have the same issue in multiverse worlds on paper.
```
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.WorldServer.<init>(net.minecraft.server.MinecraftServer, java.util.concurrent.Executor, net.minecraft.world.level.storage.Convertable$ConversionSession, net.minecraft.world.level.storage.IWorldDataServer, net.minecraft.resources.ResourceKey, net.minecraft.world.level.dimension.DimensionManager, net.minecraft.server.level.progress.WorldLoadListener, net.minecraft.world.level.chunk.ChunkGenerator, boolean, long, java.util.List, boolean, org.bukkit.World$Environment, org.bukkit.generator.ChunkGenerator)'
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.doRegen(Spigot_v1_17_R1_2.java:625) ~[worldedit-bukkit-7.2.6.jar:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2.regenerate(Spigot_v1_17_R1_2.java:578) ~[worldedit-bukkit-7.2.6.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:216) ~[worldedit-bukkit-7.2.6.jar:?]
```

**Comment by octylFractal** [comment]
You're actually just out of date on WorldEdit, #1872

**Comment by brickmonster** [comment]
Oh sorry, you're right. I updated my plugins and then waited a week before updating to 1.17 so didn't even think to check if there was a WorldEdit update. Thanks.

**Comment by pahanakun** [comment]
still an issue in 1.18.1 with fabric loader 0.12.12 and WorldEdit 7.2.8

**Comment by me4502** [comment]
Closed by https://github.com/EngineHub/WorldEdit/commit/ab61a849e87a3056677d9ff2583b8321e97ae176
