### ISSUE TITLE
Pasting area from backups are giving error 

### ISSUE THREAD

**Issue by MsKiller01** [EngineHub/WorldEdit#1966]
### WorldEdit Version

 we version [12:53:00 INFO]: WorldEdit version 7.2.9-SNAPSHOT [12:53:00 INFO]: https://github.com/EngineHub/WorldEdit/ [12:53:00 INFO]: ------------------ Platforms ------------------ * Bukkit-Official(7.2.9-SNAPSHOT+6009-4f34cf9)  [12:53:00 INFO]: ---------------- Capabilities ---------------- GAME_HOOKS: Bukkit-Official CONFIGURATION: Bukkit-Official USER_COMMANDS: Bukkit-Official PERMISSIONS: Bukkit-Official WORLDEDIT_CUI: Bukkit-Official WORLD_EDITING: Bukkit-Official

### Platform Version

> ver [12:54:31 INFO]: Checking version, please wait... [12:54:31 INFO]: This server is running Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2) You are running the latest version Previous version: git-Paper-66 (MC: 1.18) >

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

This is the error generated at console:
`[11:59:29 INFO]: WorldEdit: Using com.sk89q.worldedit.world.storage.ZippedMcRegionChunkStore for loading snapshot 'E:\Minecraft\New-New-Holland2\backups\2021-04.zip'
[11:59:30 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot invoke "com.sk89q.jnbt.CompoundTag.getValue()" because "this.rootTag" is null
        at com.sk89q.worldedit.world.chunk.AnvilChunk13.<init>(AnvilChunk13.java:64) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.world.chunk.AnvilChunk16.<init>(AnvilChunk16.java:39) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.world.storage.ChunkStoreHelper.getChunk(ChunkStoreHelper.java:104) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.world.storage.ChunkStore.getChunk(ChunkStore.java:98) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.world.snapshot.SnapshotRestore.restore(SnapshotRestore.java:143) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.LegacySnapshotUtilCommands.restore(LegacySnapshotUtilCommands.java:112) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.SnapshotUtilCommands.restore(SnapshotUtilCommands.java:75) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.SnapshotUtilCommandsRegistration.cmd$restore(SnapshotUtilCommandsRegistration.java:105) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.9-SNAPSHOT-dist.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>`

### Expected Behavior

Normally I would do restores from older backupfiles and could cope with some problems as I describe later  here, but not this time.
I really would like to be able to restore parts of the world from older backups, as seen above, backupfile from this years april till yesterday, give errors. 
I retried this today with backup from yesterday, there it gave this error ingame `Missing root 'Level' tag`
I have no idea what this means, I looked at the backupfile, and the only thing close to the word LEVEL is LEVEL.DAT and a bunch of .JSON files in the world folder...

### Reproduction Steps

1. start server
2. enter server
3. get wand
4. select are to be restored
5. do /snap list
6. pick the file I want to restore from
7. type //restore
8. behold! the error

### Anything Else?

I had removed the folder POI from backup, it seemed to work at 1.17.1 when problems arose, so I thought that I'd try that here too. It did not work.
So, I left the backup from yesterday untouched and tried it, then that gave another error, but that is for another issue I guess...

**Comment by wizjany** [comment]
https://github.com/EngineHub/WorldEdit/issues/1961#issuecomment-986569749

**Comment by MsKiller01** [comment]
THANKYOU so much, I was not aware you had this in your view, sorry to bother you guys.... You make tremendous work here, much appreciated!!!! ((-:
