### ISSUE TITLE
UseBlockEvent EventException on 1.18.1

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldEdit#1967]
### WorldEdit Version

WorldEdit v7.2.8-SNAPSHOT+6002-5ce37d7

### Platform Version

3360-Spigot-f65de01-c2e0bbd (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Testing Spigot 1.18.1. Admittedly, early days...

Every second (or so) error at the console/log
```
[10:26:52] [Server thread/ERROR]: Could not pass event UseBlockEvent to WorldGuard v7.0.7-SNAPSHOT+2165-81750e1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityInteract(EventAbstractionListener.java:568) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor219.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.BlockPressurePlateWeighted.b(BlockPressurePlateWeighted.java:46) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.world.level.block.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.world.level.block.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:64) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:911) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.level.WorldServer.d(WorldServer.java:779) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.world.ticks.TickListServer.a(SourceFile:215) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.world.ticks.TickListServer.a(SourceFile:98) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:344) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1300) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[?:?]
        at com.sk89q.worldguard.chest.SignChestProtection.isProtected(SignChestProtection.java:36) ~[?:?]
        at com.sk89q.worldguard.bukkit.BukkitWorldConfiguration.isChestProtected(BukkitWorldConfiguration.java:420) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.lambda$onUseBlock$4(ChestProtectionListener.java:129) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.onUseBlock(ChestProtectionListener.java:129) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 28 more
Caused by: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
        at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[?:?]
        at com.sk89q.worldguard.chest.SignChestProtection.isProtected(SignChestProtection.java:36) ~[?:?]
        at com.sk89q.worldguard.bukkit.BukkitWorldConfiguration.isChestProtected(BukkitWorldConfiguration.java:420) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.lambda$onUseBlock$4(ChestProtectionListener.java:129) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[?:?]
        at com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.ChestProtectionListener.onUseBlock(ChestProtectionListener.java:129) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 28 more
```

### Expected Behavior

Normal execution

### Reproduction Steps

1. Upgrade from Spigot 1.18-3359 to Spigot 1.18.1-3360
2. Start server
3. Review console/log

### Anything Else?

WorldGuard 7.0.7-SNAPSHOT+2165-81750e1

**Comment by wizjany** [comment]
X https://i.imgur.com/mBKFnzf.png
