### ISSUE TITLE
1.18.1 NOT LOADING "Java.lang.NosuchMethodError: 'long.net.minecraft.SystemUtils.b" 

### ISSUE THREAD

**Issue by takemurakiriko** [EngineHub/WorldEdit#1969]
### WorldEdit Version

7.2.8+6008-1246d61

### Platform Version

Spigot-Craftbukkit-1.18.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

There is a problem with this version. "Java.lang.NosuchMethodError: 'long.net.minecraft.SystemUtils.b" when running Craftbukkit creation in this version
This error pops up. Please correct.

### Expected Behavior

[00:29:15] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'long net.minecraft.SystemUtils.b()'
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter$MojangWatchdog.tick(PaperweightAdapter.java:992) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter.tickWatchdog(PaperweightAdapter.java:946) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWatchdog.tick(BukkitWatchdog.java:35) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.onOperation(WatchdogTickingExtent.java:74) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.setBiome(WatchdogTickingExtent.java:95) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.ChangeSetExtent.setBiome(ChangeSetExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBiome(EditSession.java:676) ~[?:?]
        at com.sk89q.worldedit.function.biome.BiomeReplace.apply(BiomeReplace.java:66) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommands.setBiome(BiomeCommands.java:181) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$_setbiome(BiomeCommandsRegistration.java:171) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:779) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1888) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1741) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1722) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:29) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1115) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1094) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1087) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1071) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1002) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:294) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>

### Reproduction Steps

[00:29:15] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'long net.minecraft.SystemUtils.b()'
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter$MojangWatchdog.tick(PaperweightAdapter.java:992) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter.tickWatchdog(PaperweightAdapter.java:946) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWatchdog.tick(BukkitWatchdog.java:35) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.onOperation(WatchdogTickingExtent.java:74) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.setBiome(WatchdogTickingExtent.java:95) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.ChangeSetExtent.setBiome(ChangeSetExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBiome(AbstractDelegateExtent.java:109) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBiome(EditSession.java:676) ~[?:?]
        at com.sk89q.worldedit.function.biome.BiomeReplace.apply(BiomeReplace.java:66) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommands.setBiome(BiomeCommands.java:181) ~[?:?]
        at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$_setbiome(BiomeCommandsRegistration.java:171) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:779) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1888) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1741) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1722) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:29) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1115) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1094) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1087) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1071) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1002) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:294) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>

**Comment by wizjany** [comment]
`Spigot-Craftbukkit-1.18.1` uhhhh, no that's just craftbukkit.
