### ISSUE TITLE
Unable to Set or Replace blocks with new version 

### ISSUE THREAD

**Issue by fray68** [EngineHub/WorldEdit#1972]
### WorldEdit Version

WorldEdit 7.2.8 (1.13.2 - 1.18.1)

### Platform Version

CraftBukkit version 3360-Bukkit-c2e0bbd (MC: 1.18.1)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

First attempted to set an area of blocks to air, received error.
Seconds attempt to replace an area of grass blocks to air, received error.

Second error details:

[20:36:48] [Server thread/INFO]: <user> issued server command: //replace grass_block air
[20:36:48] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchMethodError: 'long net.minecraft.SystemUtils.b()'
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter$MojangWatchdog.tick(PaperweightAdapter.java:992) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter.tickWatchdog(PaperweightAdapter.java:946) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWatchdog.tick(BukkitWatchdog.java:35) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:122) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[?:?]
        at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83) ~[?:?]
        at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:93) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[?:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
        at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[?:?]
        at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:779) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1888) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1741) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1722) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:29) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1115) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1094) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1087) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1071) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1002) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:294) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3360-Bukkit-c2e0bbd]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Expected Behavior

First attempt, expected blocks to be converted to air.
Second attempt, expected grass_blocks to be converted to air.

### Reproduction Steps

1. ... Mouse click position x; mouse click position y... //set air
2. ... Mouse click position x: mouse click position y... //replace grass_block air

**Comment by wizjany** [comment]
use paper (or at least spigot). this may be fixed in dev builds but you really shouldn't be using craftbukkit.
