### ISSUE TITLE
java.lang.NoSuchMethodError: 'long net.minecraft.SystemUtils.b()'

### ISSUE THREAD

**Issue by Lilyp3892** [EngineHub/WorldEdit#1978]
### WorldEdit Version

7.2.8

### Platform Version

Bukkit 1.18.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I installed the latest version of WE on the latest version of bukkit and whenever I run a WE command this comes up in the console
`java.lang.NoSuchMethodError: 'long net.minecraft.SystemUtils.b()'
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter$MojangWatchdog.tick(PaperweightAdapter.java:992) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter.tickWatchdog(PaperweightAdapter.java:946) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWatchdog.tick(BukkitWatchdog.java:35) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockState.generateStateMap(BlockState.java:122) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.lambda$new$3(BlockType.java:61) ~[?:?]
        at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.getBlockStatesMap(BlockType.java:91) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:83) ~[?:?]
        at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[?:?]
        at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:93) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[?:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[?:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[?:?]
        at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
`

### Expected Behavior

The command executes successfully

### Reproduction Steps

I followed these steps to set up a server https://www.bennetrichter.de/en/tutorials/minecraft-server-linux/ and used bukkit and replaced all 1.17.1 with 1.18.1 and I used this since its running on the google cloud

**Comment by wizjany** [comment]
duplicate

**Comment by Lilyp3892** [comment]
of what

**Comment by octylFractal** [comment]
#1969

**Comment by octylFractal** [comment]
also #1972
