### ISSUE TITLE
java.lang.ClassCastException when trying to load schematic

### ISSUE THREAD

**Issue by Phoenix616** [EngineHub/WorldEdit#2002]
### WorldEdit Version

7.3.0-SNAPSHOT+6046-757bef1

### Platform Version

git-Paper-406

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Schematic doesn't load anymore and errors

Error:
```
[19:32:55] [Server thread/INFO]: Phoenix616 issued server command: //schem load we_load_error
[19:32:55] [WorldEdit Task Executor - 0/ERROR]: Uncaught exception occurred in task: Loading schematic we_load_error
java.lang.ClassCastException: class com.sk89q.worldedit.util.nbt.CompoundBinaryTagImpl cannot be cast to class com.sk89q.jnbt.CompoundTag (com.sk89q.worldedit.util.nbt.CompoundBinaryTagImpl and com.sk89q.jnbt.CompoundTag are in unnamed module of loader 'WorldEdit.jar' @636f5edc)
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_17_R1_2.PaperweightDataConverters.fixUp(PaperweightDataConverters.java:87) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:251) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:125) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[WorldEdit.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) ~[patched_1.17.1.jar:git-Paper-406]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57) ~[patched_1.17.1.jar:git-Paper-406]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) ~[patched_1.17.1.jar:git-Paper-406]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behavior

Schematic loads

### Reproduction Steps

Try to load [this schematic](https://minebench.de/files/we_load_error.schematic) (github zip upload:[we_load_error.zip](https://github.com/EngineHub/WorldEdit/files/7833789/we_load_error.zip))

**Comment by wizjany** [comment]
this is from merging the 1.17 adapters into master. just stick to 7.2.x, don't think we want to deal with this atm because it requires doing multi-version paperweight adapters.
