### ISSUE TITLE
WorldEdit doesn't load on Spigot 1.18.2

### ISSUE THREAD

**Issue by josephjthomas** [EngineHub/WorldEdit#2044]
### WorldEdit Version

v7.2.10-SNAPSHOT+6117-e21ab6a

### Platform Version

3450-Spigot-fb0dd5f-4ed5af5 (MC: 1.18.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldEdit plugin doesn't load:

```
[11:42:09] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.10-SNAPSHOT+6117-e21ab6a
[11:42:10] [Server thread/ERROR]: Error occurred while enabling WorldEdit v7.2.10-SNAPSHOT+6117-e21ab6a (Is it up to date?)
java.lang.IllegalAccessError: failed to access class org.bukkit.plugin.java.PluginClassLoader from class com.sk89q.bukkit.util.ClassSourceValidator (org.bukkit.plugin.java.PluginClassLoader is in unnamed module of loader java.net.URLClassLoader @4534b60d; com.sk89q.bukkit.util.ClassSourceValidator is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @60a78be5)
	at com.sk89q.bukkit.util.ClassSourceValidator.<clinit>(ClassSourceValidator.java:50) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:233) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1009) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Expected Behavior

It should load

### Reproduction Steps

1. Download WorldEdit
2. Launch Spigot server
3. It doesn't work

**Comment by me4502** [comment]
Provide full logs

**Comment by josephjthomas** [comment]
```
[12:03:42] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:03:45] [Worker-Main-17/INFO]: Loaded 7 recipes
[12:03:47] [Server thread/INFO]: Starting minecraft server version 1.18.2
[12:03:47] [Server thread/INFO]: Loading properties
[12:03:47] [Server thread/INFO]: This server is running CraftBukkit version 3450-Spigot-fb0dd5f-4ed5af5 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
[12:03:47] [Server thread/INFO]: Debug logging is disabled
[12:03:47] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:03:47] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:03:47] [Server thread/INFO]: Default game type: SURVIVAL
[12:03:47] [Server thread/INFO]: Generating keypair
[12:03:48] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:03:48] [Server thread/INFO]: Using default channel type
[12:03:49] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.10-SNAPSHOT+6117-e21ab6a
[12:03:49] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@43c69053]
[12:03:49] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.10-SNAPSHOT+6117-e21ab6a
[12:03:49] [Server thread/ERROR]: Error occurred while enabling WorldEdit v7.2.10-SNAPSHOT+6117-e21ab6a (Is it up to date?)
java.lang.IllegalAccessError: failed to access class org.bukkit.plugin.java.PluginClassLoader from class com.sk89q.bukkit.util.ClassSourceValidator (org.bukkit.plugin.java.PluginClassLoader is in unnamed module of loader java.net.URLClassLoader @18769467; com.sk89q.bukkit.util.ClassSourceValidator is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @251c6ba7)
	at com.sk89q.bukkit.util.ClassSourceValidator.<clinit>(ClassSourceValidator.java:50) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:233) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1009) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3450-Spigot-fb0dd5f-4ed5af5]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:03:49] [Server thread/INFO]: Preparing level "world"
[12:03:50] [Server thread/INFO]: -------- World Settings For [world] --------
[12:03:50] [Server thread/INFO]: Item Merge Radius: 2.5
[12:03:50] [Server thread/INFO]: Item Despawn Rate: 6000
[12:03:50] [Server thread/INFO]: View Distance: 10
[12:03:50] [Server thread/INFO]: Simulation Distance: 10
[12:03:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:03:50] [Server thread/INFO]: Mob Spawn Range: 6
[12:03:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:03:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Carrot Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Potato Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Kelp Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:03:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[12:03:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:03:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[12:03:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:03:50] [Server thread/INFO]: Max TNT Explosions: 100
[12:03:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:03:50] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[12:03:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:03:50] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[12:03:50] [Server thread/INFO]: Item Merge Radius: 2.5
[12:03:50] [Server thread/INFO]: Item Despawn Rate: 6000
[12:03:50] [Server thread/INFO]: View Distance: 10
[12:03:50] [Server thread/INFO]: Simulation Distance: 10
[12:03:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:03:50] [Server thread/INFO]: Mob Spawn Range: 6
[12:03:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:03:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Carrot Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Potato Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Kelp Growth Modifier: 100%
[12:03:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:03:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[12:03:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:03:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[12:03:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:03:50] [Server thread/INFO]: Max TNT Explosions: 100
[12:03:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:03:50] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[12:03:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:03:51] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[12:03:51] [Server thread/INFO]: Item Merge Radius: 2.5
[12:03:51] [Server thread/INFO]: Item Despawn Rate: 6000
[12:03:51] [Server thread/INFO]: View Distance: 10
[12:03:51] [Server thread/INFO]: Simulation Distance: 10
[12:03:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:03:51] [Server thread/INFO]: Mob Spawn Range: 6
[12:03:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:03:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Carrot Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Potato Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Kelp Growth Modifier: 100%
[12:03:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:03:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[12:03:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:03:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[12:03:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:03:51] [Server thread/INFO]: Max TNT Explosions: 100
[12:03:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:03:51] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[12:03:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:03:51] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:03:52] [Worker-Main-27/INFO]: Preparing spawn area: 0%
[12:03:52] [Worker-Main-24/INFO]: Preparing spawn area: 0%
[12:03:52] [Worker-Main-30/INFO]: Preparing spawn area: 0%
[12:03:52] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[12:03:53] [Worker-Main-28/INFO]: Preparing spawn area: 0%
[12:03:53] [Worker-Main-25/INFO]: Preparing spawn area: 2%
[12:03:54] [Worker-Main-30/INFO]: Preparing spawn area: 5%
[12:03:54] [Worker-Main-29/INFO]: Preparing spawn area: 13%
[12:03:55] [Worker-Main-29/INFO]: Preparing spawn area: 60%
[12:03:55] [Server thread/INFO]: Time elapsed: 4363 ms
[12:03:55] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[12:03:56] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[12:03:56] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[12:03:56] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[12:03:57] [Worker-Main-26/INFO]: Preparing spawn area: 0%
[12:03:57] [Worker-Main-26/INFO]: Preparing spawn area: 95%
[12:03:57] [Server thread/INFO]: Time elapsed: 2012 ms
[12:03:57] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[12:03:57] [Worker-Main-26/INFO]: Preparing spawn area: 0%
[12:03:58] [Worker-Main-27/INFO]: Preparing spawn area: 9%
[12:03:58] [Server thread/INFO]: Time elapsed: 816 ms
[12:03:58] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:03:58] [Server thread/INFO]: Done (8.416s)! For help, type "help"
```

**Comment by NotMyFault** [comment]
For reference, that appears to be a Spigot only issue. WorldEdit works fine on the newest Paper builds for 1.18.1 and .2
