### ISSUE TITLE
Error when using WorldEdit with version 7.2.10 snapshot on version 1.18.2 server

### ISSUE THREAD

**Issue by xs7884** [EngineHub/WorldEdit#2053]
### WorldEdit Version

worldedit-bukkit-7.2.10-SNAPSHOT-dist

### Platform Version

paper-1.18.2-235

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[12:24:42] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.extent.EditSessionEvent@1a020e40 to handler EventHandler{priority=VERY_EARLY}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.EditSession.wrapExtent(EditSession.java:318) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:271) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1048) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:249) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:408) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2108) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2089) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-235]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-235]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/fastasyncworldedit/core/regions/RegionWrapper
	at com.plotsquared.core.util.WEManager.getMask(WEManager.java:95) ~[PlotSquared-Bukkit-6.6.0-Premium.jar:?]
	at com.plotsquared.core.listener.WESubscriber.onEditSession(WESubscriber.java:96) ~[PlotSquared-Bukkit-6.6.0-Premium.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	... 57 more
Caused by: java.lang.ClassNotFoundException: com.fastasyncworldedit.core.regions.RegionWrapper
	at com.plotsquared.core.util.WEManager.getMask(WEManager.java:95) ~[PlotSquared-Bukkit-6.6.0-Premium.jar:?]
	at com.plotsquared.core.listener.WESubscriber.onEditSession(WESubscriber.java:96) ~[PlotSquared-Bukkit-6.6.0-Premium.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.10-SNAPSHOT-dist.jar:?]
	... 57 more

### Expected Behavior

Whenever I use the 7.2.10 snapshot version worldedit command (//set, etc.) on the 1.18.2 version server, the above error is output.

### Reproduction Steps

1. ...
2. ...

**Comment by octylFractal** [comment]
Seems like an issue with plotsquared premium needing FAWE. Take it up with them.
