### ISSUE TITLE
7.2.10 error

### ISSUE THREAD

**Issue by ricsal1** [EngineHub/WorldEdit#2068]
### WorldEdit Version

7.2.10

### Platform Version

paper-1.18.2-260

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Eclipse OpenJ9 VM openj9-0.29.1) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[20:42:06 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:42:07 INFO]: Loaded 7 recipes
[20:42:09 INFO]: Starting minecraft server version 1.18.2
[20:42:09 INFO]: Loading properties
[20:42:09 INFO]: This server is running Paper version git-Paper-260 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: bc68ee0)
[20:42:09 INFO]: Using 4 threads for Netty based IO
[20:42:09 INFO]: Server Ping Player Sample Count: 12
[20:42:09 INFO]: Default game type: SURVIVAL
[20:42:09 INFO]: Generating keypair
[20:42:10 INFO]: Starting Minecraft server on *:25599
[20:42:10 INFO]: Using default channel type
[20:42:10 INFO]: Paper: Using Java 11 compression from Velocity.
[20:42:10 INFO]: Paper: Using Java cipher from Velocity.
[20:42:10 ERROR]: Could not load 'plugins\worldedit-mod-7.2.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer$$Lambda$4123/0x00000000b08c4bd8.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 8 more

### Expected Behavior

no erros

### Reproduction Steps

after update from 7.2.9

**Comment by wizjany** [comment]
you downloaded the wrong thing
