### ISSUE TITLE
Plugin.YML not found in .jar

### ISSUE THREAD

**Issue by Karbzee** [EngineHub/WorldEdit#2069]
### WorldEdit Version

7.2.10

### Platform Version

paper-1.18.2-261

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Upon launching my paper MC server (paper-1.18.2-261), with the latest version of world edit (7.2.10) that is compatible with 1.18.2 I find that world edit is unable to load due to a missing file within the  .JAR.  The previous version I used (7.2.9) contains the .YML file which is missing from the latest .JAR build.

### Expected Behavior

I would expect the plugin to load properly, and expect core functions to be usable.

### Reproduction Steps

1.  Create a server with Paper-1.18.2-(any version)

2.  Install the latest version of world edit (7.2.10)

3. Launch your server, and monitor console to find that world edit is not able to load due to a missing .YML file.

### Anything Else?

`[20:32:57] [Server thread/ERROR]: Could not load 'plugins\worldedit-mod-7.2.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-249]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml`

![image](https://user-images.githubusercontent.com/74452851/159116302-5ead89b9-4d78-4e67-a5e7-aab163dbd4f5.png)

**Comment by me4502** [comment]
You're using the version for Fabric on Paper. Use the Bukkit version.

**Comment by Karbzee** [comment]
@me4502 

I'm sorry for the tag, but is there an expected date of when the version for Bukkit will be updated to support Paper 1.18.2 - As currently there are no releases for it.

**Comment by me4502** [comment]
That's entirely out of our control - it depends when BukkitDev approve the jar file. You can use builds here for now https://builds.enginehub.org/job/worldedit

**Comment by Karbzee** [comment]
Thank you for the prompt response. @me4502 Muchly appreciated.
