### ISSUE TITLE
plugin missing file Jar does not contain plugin.yml

### ISSUE THREAD

**Issue by regchanuk** [EngineHub/WorldEdit#2072]
### WorldEdit Version

worldedit-mod-7.2.10.ja

### Platform Version

paper1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

ERROR09:02:57
Could not load 'plugins/worldedit-mod-7.2.10.jar' in folder 'plugins'
Console09:02:57
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-265]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-265]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-265]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-265]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

### Expected Behavior

to load plugin

### Reproduction Steps

restart server did not work 

### Anything Else?

nope just requires a fix

**Comment by regchanuk** [comment]
its a bug why closed reason required

**Comment by me4502** [comment]
You're using worldedit for fabric. If you want it to work on Bukkit use worldedit for Bukkit

**Comment by regchanuk** [comment]
can now be closed
