### ISSUE TITLE
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by Justman10000** [EngineHub/WorldEdit#2074]
### WorldEdit Version

7.2.10

### Platform Version

Spigot 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

>>> Could not load 'plugins/worldedit-mod-7.2.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:406) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 7 more

### Expected Behavior

No errors an the plugin has started

### Reproduction Steps

1. Install the newest Version of WorldEdit (7.2.10)
2. Install WorldEdit on the latest Minecraft Server Software (1.18.2)
3. Start/Restart the server

**Comment by Justman10000** [comment]
@wizjany 

Ah, nice that no one answers! And it's a bug of WorldEdit!

**Comment by octylFractal** [comment]
Consider using the search function before making an issue next time: https://github.com/EngineHub/WorldEdit/issues?q=InvalidDescriptionException+is%3Aissue+is%3Aclosed. We've answered this 4 times before.
