### ISSUE TITLE
WorldEdit 7.2.11 Beta 1 crash

### ISSUE THREAD

**Issue by vedroyder** [EngineHub/WorldEdit#2131]
### WorldEdit Version

WorldEdit 7.2.11 Beta 1

### Platform Version

Forge 41.0.62 (1.19)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Crash on start

### Expected Behavior

To not crash

### Reproduction Steps

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 30.06.2022, 17:35
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23182%23189!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23182%23189!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:552) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.ifElse(Util.java:432) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:546) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.render(LoadingOverlay.java:135) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:885) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1070) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:660) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-1.19-41.0.62_mapped_official_1.19-recomp.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:25) ~[fmlloader-1.19-41.0.62.jar%2394!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%23106!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128) [idea_rt.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sk89q.worldedit.forge.ForgeDataFixer.<clinit>(ForgeDataFixer.java:179) ~[worldedit-mod-7.2.11-beta-01.jar%23181!/:?] {re:classloading}
-- MOD worldedit --
Details:
	Mod File: worldedit-mod-7.2.11-beta-01.jar
	Failure message: WorldEdit (worldedit) encountered an error during the common_setup event phase
		java.lang.NoSuchFieldError: f_128958_
	Mod Version: 7.2.11-beta-01+6200-0877589
	Mod Issue URL: https://discord.gg/enginehub
	Exception message: java.lang.NoSuchFieldError: f_128958_
Stacktrace:
	at com.sk89q.worldedit.forge.ForgeDataFixer.<clinit>(ForgeDataFixer.java:179) ~[worldedit-mod-7.2.11-beta-01.jar%23181!/:?] {re:classloading}
	at com.sk89q.worldedit.forge.ForgePlatform.<init>(ForgePlatform.java:75) ~[worldedit-mod-7.2.11-beta-01.jar%23181!/:?] {re:classloading}
	at com.sk89q.worldedit.forge.ForgeWorldEdit.setupPlatform(ForgeWorldEdit.java:162) ~[worldedit-mod-7.2.11-beta-01.jar%23181!/:?] {re:classloading}
	at com.sk89q.worldedit.forge.ForgeWorldEdit.init(ForgeWorldEdit.java:153) ~[worldedit-mod-7.2.11-beta-01.jar%23181!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%23105!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%23105!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%23105!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%23105!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.62.jar%23184!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.0.62.jar%23187!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 581210112 bytes (554 MiB) / 1083179008 bytes (1033 MiB) up to 1589641216 bytes (1516 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-4150T CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2,99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: LogMeIn Mirror Driver
	Graphics card #0 vendor: LogMeIn, Inc.
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=7.1.542.0
	Graphics card #1 name: NVIDIA GeForce 800M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048,00
	Graphics card #1 deviceId: 0x1140
	Graphics card #1 versionInfo: DriverVersion=23.21.13.9135
	Memory slot #0 capacity (MB): 2048,00
	Memory slot #0 clockSpeed (GHz): 1,07
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 15138,94
	Virtual memory used (MB): 12331,21
	Swap memory total (MB): 9082,19
	Swap memory used (MB): 2414,25
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclientuserdev
	ModLauncher naming: mcp
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		forge-1.19-41.0.62_mapped_official_1.19-recomp.jar|Minecraft                     |minecraft                     |1.19                |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		main                                              |Traders and Bandits           |tradersandbandits             |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
		                                                  |Forge                         |forge                         |41.0.62             |SIDED_SETU|Manifest: NOSIGNATURE
		worldedit-mod-7.2.11-beta-01.jar                  |WorldEdit                     |worldedit                     |7.2.11-beta-01+6200-|ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 653848fd-6230-472d-b2db-6f2ebffc3da0
	FML: 41.0
	Forge: net.minecraftforge:41.0.62
```

**Comment by vedroyder** [comment]
fixed it, thanks.
