### ISSUE TITLE
schematic paste error

### ISSUE THREAD

**Issue by Yamiru** [EngineHub/WorldEdit#2138]
### WorldEdit Version

Bukkit-Official(7.3.0-SNAPSHOT+6204-a8b5268)

### Platform Version

Paper  1.19 #58

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

after paste worldedit schematic "endgateway"

```
[11:07:59 ERROR]: Uncaught exception occurred in task: Loading schematic endgateway
java.lang.ClassCastException: class com.sk89q.worldedit.util.nbt.CompoundBinaryTagImpl cannot be cast to class com.sk89q.jnbt.CompoundTag (com.sk89q.worldedit.util.nbt.CompoundBinaryTagImpl and com.sk89q.jnbt.CompoundTag are in unnamed module of loader 'worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar' @5d7e9f58)
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R1.PaperweightDataConverters.fixUp(PaperweightDataConverters.java:86) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.VersionedDataFixer.fixUp(VersionedDataFixer.java:45) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.ReaderUtil.initializeClipboardFromBlocks(ReaderUtil.java:173) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV1Reader.readVersion1(SpongeSchematicV1Reader.java:148) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.doRead(SpongeSchematicV2Reader.java:87) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.read(SpongeSchematicV2Reader.java:75) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.3.0-SNAPSHOT-dist.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.0.1-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.0.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behavior

pasting schematic to folder worldedit/schematics and execute ingame

### Reproduction Steps

1. copy **endgateway.schem** to schematics
2. paste
3. error
4. rename **endgateway.schem** to **endgateway.schematic**
5. paste
6. same problem

### Anything Else?

thank you

**Comment by me4502** [comment]
WorldEdit 7.3.0 is currently not usable, pending some NBT changes. You should not be using the next release target and instead should be using 7.2.x releases.
