### ISSUE TITLE
World edit not workin

### ISSUE THREAD

**Issue by Joche777** [EngineHub/WorldEdit#2169]
### WorldEdit Version

7.2.10

### Platform Version

Forge 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Error occurred while enabling WorldEdit v7.2.10+1742f98 (Is it up to date?)
java.lang.IllegalStateException: key 'minecraft:ocean' already has an associated biome type
        at com.google.common.base.Preconditions.checkState(Preconditions.java:821) ~[guava-31.0.1-jre.jar%2323!/:?]
        at com.sk89q.worldedit.registry.Registry.register(Registry.java:56) ~[worldedit-mod-7.2.10.jar%23187!/:?]
        at com.sk89q.worldedit.registry.NamespacedRegistry.register(NamespacedRegistry.java:55) ~[worldedit-mod-7.2.10.jar%23187!/:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.initializeRegistries(WorldEditPlugin.java:214) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServerMixin.java:2590) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.Bukkit.reload(Bukkit.java:801) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServerMixin.java:826) ~[arclight-1.18.2-1.0.6-7e754e7e.jar%2368!/:arclight-1.18.2-1.0.6-7e754e7e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerPlayNetHandlerMixin.java:2592) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerPlayNetHandlerMixin.java:2435) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerPlayNetHandlerMixin.java:2422) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.network.protocol.PacketUtils.md4e8969$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23190!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Expected Behavior

a

### Reproduction Steps

1. ...
2. ...
a

### Anything Else?

a

**Comment by me4502** [comment]
Don’t lie when filling out an issue report
