### ISSUE TITLE
Error using //drawsel on

### ISSUE THREAD

**Issue by SamLiprandi** [EngineHub/WorldEdit#2201]
### WorldEdit Version

bukkit 7.2.12

### Platform Version

spigot-1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When using the command `//drawsel on` I get the following error in the server console: 

```
[17:53:45] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchFieldError: networkManager
at com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R1.PaperweightAdapter.sendFakeNBT(PaperweightAdapter.java:528) ~[?:?]
at com.sk89q.worldedit.bukkit.BukkitPlayer.sendFakeBlock(BukkitPlayer.java:302) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlayerProxy.sendFakeBlock(PlayerProxy.java:189) ~[?:?]
at com.sk89q.worldedit.LocalSession.updateServerCUI(LocalSession.java:837) ~[?:?]
at com.sk89q.worldedit.LocalSession.dispatchCUISelection(LocalSession.java:882) ~[?:?]
at com.sk89q.worldedit.command.SelectionCommands.select(SelectionCommands.java:651) ~[?:?]
at com.sk89q.worldedit.command.SelectionCommandsRegistration.cmd$_sel(SelectionCommandsRegistration.java:539) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1949) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1914) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3586-Spigot-4c157bb-5cc9c02]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

Moreover, the after that multiple bugs persists until I call the command `//drawsel off` such as left clicking blocks with the wooden axe marking the first position but still destroying the targeted block.

### Expected Behavior

The usual behavior of `//drawsel on`

### Reproduction Steps

1. Start up server and load world
2. Login onto the server
3. Type `//drawsel on` in game

### Other plugins installed
Here is the list of all the other plugins installed in case there is an incompatibility I wasn't able to find:
- Big Doors 0.1.8.40
- Core Protect 21.2
- EssentialsX 2.20.0
- EssentialsXChat 2.20.0
- EssentialsXSpawn 2.20.0
- Luck Perms Bukkit 5.4.49
- Multiverse Core 4.3.1
- Multiverse Inventories 4.2.3
- Multiverse Nether Portals 4.2.2
- Multiverse Portals 4.2.1
- Nametag Edit 4.5.11
- OpenInv 4.2.1
- Simple Sit 1.7
- TrollBoss 6.5.2
- TwitchSync 1.4.2
- Uber Encahnt 8.9.7
- Vault 1.7.3
- Worldguard Bukkit 7.0.8-beta-01

**Comment by me4502** [comment]
As you haven't provided a specific Spigot build, this is extremely difficult to comment on. It's quite possible you're using an early Spigot build prior to 1.19.2 being stable. I cannot reproduce this
