### ISSUE TITLE
Nickname of blocks causing massive null errors.

### ISSUE THREAD

**Issue by Wolvend** [EngineHub/WorldEdit#2202]
### WorldEdit Version

Bukkit-Offical 7.2.12+6240-87f4ae1

### Platform Version

Purpur 1.19.2-r0-1 SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Any nickname of blocks causing massive null errors.

### Expected Behavior

Big error when you don't type the specific block name for something.

cyan instead of cyan_wool

For some reason the ID for blocks like dirt (2,3,4) don't cause this issue.

### Reproduction Steps

//set cyan

### Anything Else?

[17:51:24 INFO]: Wolvend issued server command: //set cyan
[17:51:24 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.<init>(CraftItemStack.java:97) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:76) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at dev.lone.itemsadder.NMS.nbt.nms.impl.CraftItemStack_v1_19_R1_2.a(SourceFile:34) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.NMS.nbt.nms.impl.CraftItemStack_v1_19_R1_2.g(SourceFile:18) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.NMS.nbt.NItem.<init>(SourceFile:19) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:36) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:29) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.<init>(SourceFile:35) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:57) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:66) ~[ItemsAdder_3.2.3-r10.jar:?]
        at dev.lone.iaedit.CustomBlocksInputParser.parseFromInput(CustomBlocksInputParser.java:73) ~[ItemsAdder-WorldEdit_1.1.2(2).jar:?]
        at dev.lone.iaedit.CustomBlocksInputParser.parseFromInput(CustomBlocksInputParser.java:23) ~[ItemsAdder-WorldEdit_1.1.2(2).jar:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:98) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.extension.factory.ExtendedBlockFactory.parseFromInput(ExtendedBlockFactory.java:75) ~[?:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[worldedit-bukkit-7.2.12.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.12.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.12.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:51:29 INFO]: Wolvend issued server command: //undo

**Comment by wizjany** [comment]
purely an issue with whatever itemsadder is doing.
