### ISSUE TITLE
Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@6b623ba

### ISSUE THREAD

**Issue by sprocketaudio** [EngineHub/WorldEdit#2210]
### WorldEdit Version

worldedit-mod-7.2.12.jar

### Platform Version

Forge 1.19.2-43.1.47

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@6b623ba on server load

Cant get full log as no crash report - this is from debug log:

[Server thread/ERROR] [com.sk89q.worldedit.util.eventbus.EventBus/]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@6b623ba to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.forge.ForgeWorldEdit.serverStarted(ForgeWorldEdit.java:259) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.forge.__ForgeWorldEdit_serverStarted_ServerStartedEvent.invoke(.dynamic) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:109) ~[forge-1.19.2-43.1.47-universal.jar%23383!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:629) ~[server-1.19.2-20220805.130853-srg.jar%23378!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23378!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class com.sk89q.worldedit.util.Direction cannot be cast to class java.lang.String (com.sk89q.worldedit.util.Direction is in module worldedit@7.2.12+6240-87f4ae1 of loader 'TRANSFORMER' @6ef1c3f7; java.lang.String is in module java.base of loader 'bootstrap')
	at com.sk89q.worldedit.forge.internal.ForgeTransmogrifier.transmogToMinecraftProperties(ForgeTransmogrifier.java:104) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.forge.internal.ForgeTransmogrifier.transmogToMinecraft(ForgeTransmogrifier.java:118) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.forge.ForgeAdapter.adapt(ForgeAdapter.java:181) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.forge.ForgeBlockRegistry.getInternalBlockStateId(ForgeBlockRegistry.java:74) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.extension.platform.Capability$4.ready(Capability.java:100) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleNewPlatformReady$0(PlatformManager.java:330) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformManager.handleNewPlatformReady(PlatformManager.java:330) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.2.12.jar%23366!/:?]
	... 11 more

### Expected Behavior

Server should load

### Reproduction Steps

Install mod into atm8

Start server

**Comment by me4502** [comment]
This looks like one of your mods is adding a block with a property of an invalid type

**Comment by sprocketaudio** [comment]
uuh.. its atm8 :( I guess there no way to track it?

**Comment by me4502** [comment]
You'd likely need to remove groups of mods until it works again, then re-add that last removed group one by one until it breaks. Then you can report it to the offending mod
