### ISSUE TITLE
Pasting block entities is broken on SpongeVanilla 1.16.5

### ISSUE THREAD

**Issue by avaruus1** [EngineHub/WorldEdit#2238]
### WorldEdit Version

7.2.11+c43a877

### Platform Version

SpongeVanilla: 1.16.5-8.1.0-RC1246

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Pasting block entities is not possible. An exception (see below) is thrown.

### Expected Behavior

Pasting block entities should be possible.

### Reproduction Steps

1. Make a selection that contains a block entity
2. //copy
3. //paste

### Anything Else?

Attempting to paste block entities results in the following exception:
```
[15:45:36] [Server thread/ERROR] [c.sk8.wor.uti.eve.EventBus]: Could not dispatch event: com.sk89q.worldedit.event.platform.CommandEvent@54ee8e8f to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[EventHandler.class:7.2.11]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[EventBus.class:7.2.11]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[EventBus.class:7.2.11]
        at com.sk89q.worldedit.sponge.SpongeWorldEdit$1.process(SpongeWorldEdit.java:261) ~[SpongeWorldEdit$1.class:7.2.11]
        at org.spongepowered.common.command.registrar.SpongeRawCommandRegistrar.process(SpongeRawCommandRegistrar.java:90) ~[SpongeRawCommandRegistrar.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.vanilla.launch.command.VanillaCommandManager.processCommand(VanillaCommandManager.java:46) ~[VanillaCommandManager.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.common.command.manager.SpongeCommandManager.process(SpongeCommandManager.java:355) ~[SpongeCommandManager.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.execute(SpongeCommandDispatcher.java:126) ~[SpongeCommandDispatcher.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:70) ~[DelegatingCommandDispatcher.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:45) ~[DelegatingCommandDispatcher.class:1.16.5-8.1.0-RC1246]
        at net.minecraft.commands.Commands.performCommand(Commands.java:249) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:1211) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1198) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1177) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:36) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:9) ~[?:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:262) ~[PacketPhaseUtil.class:1.16.5-8.1.0-RC1246]
        at net.minecraft.network.protocol.PacketUtils.md2bedac$lambda$tracker$redirectProcessPacket$0$0(PacketUtils.java:552) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:144) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zdf000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4822) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:761) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:155) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:743) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:737) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:722) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:257) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.api.registry.ValueNotFoundException: No 'minecraft:block_entity_type' registry has been defined in root 'minecraft:root'
        at org.spongepowered.common.registry.RegistryHolderLogic.registry(RegistryHolderLogic.java:104) ~[RegistryHolderLogic.class:1.16.5-8.1.0-RC1246]
        at org.spongepowered.common.registry.SpongeRegistryHolder.registry(SpongeRegistryHolder.java:97) ~[SpongeRegistryHolder.class:1.16.5-8.1.0-RC1246]
        at com.sk89q.worldedit.sponge.SpongeWorld.setBlock(SpongeWorld.java:198) ~[SpongeWorld.class:7.2.11]
        at com.sk89q.worldedit.extent.world.SideEffectExtent.setBlock(SideEffectExtent.java:89) ~[SideEffectExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[AbstractDelegateExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.world.SurvivalModeExtent.setBlock(SurvivalModeExtent.java:100) ~[SurvivalModeExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[AbstractDelegateExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[AbstractDelegateExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.world.ChunkLoadingExtent.setBlock(ChunkLoadingExtent.java:69) ~[ChunkLoadingExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[AbstractDelegateExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.cache.LastAccessExtentCache.setBlock(LastAccessExtentCache.java:74) ~[LastAccessExtentCache.class:7.2.11]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[AbstractDelegateExtent.class:7.2.11]
        at com.sk89q.worldedit.extent.inventory.BlockBagExtent.setBlock(BlockBagExtent.java:113) ~[BlockBagExtent.class:7.2.11]
        at com.sk89q.worldedit.function.operation.SetBlockMap.resume(SetBlockMap.java:45) ~[SetBlockMap.class:7.2.11]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder$1.resume(MultiStageReorder.java:281) ~[MultiStageReorder$1.class:7.2.11]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[OperationQueue.class:7.2.11]
        at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[OperationQueue.class:7.2.11]
        at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:74) ~[Operations.class:7.2.11]
        at com.sk89q.worldedit.EditSession.internalFlushSession(EditSession.java:938) ~[EditSession.class:7.2.11]
        at com.sk89q.worldedit.EditSession.close(EditSession.java:882) ~[EditSession.class:7.2.11]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:540) ~[PlatformCommandManager.class:7.2.11]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[MethodHandleEventHandler.class:7.2.11]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[EventHandler.class:7.2.11]
        ... 31 more
```

**Comment by me4502** [comment]
This is due to a change in Sponge, that WorldEdit is already updated for
