### ISSUE TITLE
I write the //set commands (an error occurs if you do not mark the territory, just write the commands) and as a result, an error in the console.

### ISSUE THREAD

**Issue by TheFaik** [EngineHub/WorldEdit#2242]
### WorldEdit Version

7.2.14-SNAPSHOT

### Platform Version

Purpur-1.16.5_1171

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I write the //set commands (an error occurs if you do not mark the territory, just write the commands) and as a result, an error in the console.

### Expected Behavior

I just wanted to check, that's all (I'm Russian and therefore use Google translator).

### Reproduction Steps

1. I went to the server.
2.Registered commands //set (rights are available)
3. The result is an error in the console.

### Anything Else?

Here is the error itself:
[00:00:00] [Server thread/INFO]: Nick issued server command: //set
[00:00:00] [Server thread/WARN]: com.sk89q.worldedit.IncompleteRegionException
[00:00:00] [Server thread/WARN]: 	at com.sk89q.worldedit.LocalSession.getSelection(LocalSession.java:422)
[00:00:00] [Server thread/WARN]: 	at net.mrjarousek.util.wg.wg7.checkIntersection(wg7.java:67)
[00:00:00] [Server thread/WARN]: 	at net.mrjarousek.listeners.RegionProtect.wg(RegionProtect.java:340)
[00:00:00] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[00:00:00] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:00:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2307)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152)
[00:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[00:00:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by me4502** [comment]
Not a WorldEdit error, it's whatever plugin is `net.mrjarousek.util.wg.wg7.checkIntersection`

**Comment by TheFaik** [comment]
Thank you so much!

**Comment by UntouchedOdin0** [comment]
@TheFaik this is the method causing the problem [https://github.com/RSTeamCore/WorldGuardRegionProtect/blob/dev/wgrp-bukkit/src/main/java/net/ritasister/wgrp/util/wg/wg7.java#L47-L73](url)
