### ISSUE TITLE
Unhandled exception executing tab-completer for 'mask "water >tall_seagrass[half=lower' in com.sk89q.bukkit.util.DynamicPluginCommand(mask)

### ISSUE THREAD

**Issue by Brokkonaut** [EngineHub/WorldEdit#2258]
### WorldEdit Version

Bukkit-Official(7.2.14-SNAPSHOT+6290-474c191)

### Platform Version

git-Paper-"1719345" (MC: 1.19.3)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I was typing **/mask "water >tall_seagrass[half=lower]"** i got an exception in the tab completer:

```
[04:10:57 ERROR]: Exception when Brokkonaut attempted to tab complete mask "water >tall_seagrass[half=lower
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'mask "water >tall_seagrass[half=lower' in com.sk89q.bukkit.util.DynamicPluginCommand(mask)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:246) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabCompleteCommand(CraftServer.java:2270) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabComplete(CraftServer.java:2242) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-"1719345"]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.3.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[paper-1.19.3.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:901) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-"1719345"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: End must be greater than or equal to start
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at com.sk89q.worldedit.internal.util.Substring.wrap(Substring.java:52) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.internal.command.CommandUtil.onlyOnLastQuotedWord(CommandUtil.java:236) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.internal.command.CommandUtil.lambda$fixSuggestions$10(CommandUtil.java:219) ~[WorldEdit.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.sk89q.worldedit.internal.command.CommandUtil.fixSuggestions(CommandUtil.java:223) ~[WorldEdit.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onTabComplete(WorldEditPlugin.java:393) ~[WorldEdit.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.tabComplete(DynamicPluginCommand.java:85) ~[WorldEdit.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 20 more

```

### Expected Behavior

No exceptions, but tab completions ;)

### Reproduction Steps

Type **/mask "water >tall_seagrass[half=lower** in the chat

**Comment by wizjany** [comment]
looks like #2125
