### ISSUE TITLE
//drawsel not working (java.lang.NoSuchFieldError: networkManager)

### ISSUE THREAD

**Issue by joergsesterhenn** [EngineHub/WorldEdit#2265]
### WorldEdit Version

Bukkit-Official(7.2.13+46576cc)

### Platform Version

git-paper-404

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I want to see the selection and activate //drawsel I get an error message (see below) on the console and no visualization happens.

### Expected Behavior

Worldedit draws my selection.

### Reproduction Steps

1. enter //drawsel in chat
2. get error message

### Anything Else?

[18:37:12] [Server thread/INFO]: XXXXXX issued server command: //drawsel
[18:37:12] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoSuchFieldError: networkManager
        at com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R2.PaperweightAdapter.sendFakeNBT(PaperweightAdapter.java:529) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.sendFakeBlock(BukkitPlayer.java:302) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.extension.platform.PlayerProxy.sendFakeBlock(PlayerProxy.java:189) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.LocalSession.updateServerCUI(LocalSession.java:837) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.command.GeneralCommands.drawSelection(GeneralCommands.java:326) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.command.GeneralCommandsRegistration.cmd$_drawsel(GeneralCommandsRegistration.java:354) ~[worldedit-bukkit-7.2.13.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.13.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.13.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:931) ~[paper-1.19.3.jar:git-Paper-404]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-404]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-404]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by joergsesterhenn** [comment]
I just noticed that my version of worldguard (worldguard-bukkit-7.0.7-dist.jar) was outdated and not compatible with minecraft 1.19.x. Updated this to the current beta. Maybe this could be related.

**Comment by joergsesterhenn** [comment]
![image](https://user-images.githubusercontent.com/974666/219898851-6b0830cb-e6fa-4468-81a9-b6f456af1b79.png)

**Comment by joergsesterhenn** [comment]
Updating worldedit to 7.0.8 didn't change a thing. Above is a list of my installed plugins.

**Comment by joergsesterhenn** [comment]
looks like #2201

**Comment by me4502** [comment]
I cannot reproduce this, like last time it was reported - something must be different about your setup than the standard Paper jar file

**Comment by joergsesterhenn** [comment]
I am using standard paper downloaded from their site.

Thanks for taking time to look at this in
the first place! I'd really like to get this to work.

What can I provide for you to better be able to reproduce this, or try on my side to better single out what causes this? 

I could try to make a copy of my server with only worldedit and worldguard installed and see if the behavior changes.

I also have all my servers configs in a private GitHub repo that I could share with you, if you'd want to have a look.

Is there any additional debug logging that I could enable and provide?

Thanks for your time!

**Comment by joergsesterhenn** [comment]
I just found this: https://madelinemiller.dev/blog/debug-minecraft-server-issues/

Will try this and see if I can find something. I am quite new to selfhosting  a Minecraft server. I guess I have a lot to learn.

**Comment by joergsesterhenn** [comment]
I generated a debug report with worldguard. Maybe you can see something that could determine what is wrong here:

[report.txt](https://github.com/EngineHub/WorldEdit/files/10844222/report.txt)

Instead of diving into the adventure of setting up a testserver and fixing this like I should have I went the easy way around the issue by installing another plugin to visualize the worldedit selection ... (WorldEditSelectionVisualizer) and hope that there aren't any other weird issues in my setup.

That plugin does a great job and although I am sure that drawsel would have been the better option for now I will not be looking into this issue so feel free to close this.

Should you by chance at some point in the future have any ideas what might have triggered the error please let me know.
