### ISSUE TITLE
invisible (modded) blocks after pasting or filling a selection

### ISSUE THREAD

**Issue by ink717** [EngineHub/WorldEdit#2268]
### WorldEdit Version

7.2.12

### Platform Version

Forge 43.2.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

forge version 43.2.0 and above,
the issue happens regardless of optifine, rubidium, flywheel, distant horizons is active eg.

when using worldedit to fill an area, or paste a section, or manually placing some modded blocks (e.g. desk, bricks) by hand, the other players in the server can't see it. Even breaking the block, other players can't see. it's still there, but invisible. need to teleport out of the chunk render distance and back to make the blocks show.

This doesn't happen on single player world.

### Expected Behavior

The Conosole will show this error each time the rendering issue happens, and it'll be spamming continuously if manually placing affected blocks around.

[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6933_(Level.java:198)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:165)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_7731_(Level.java:188)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_233647_(ClientLevel.java:142)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.prediction.BlockStatePredictionHandler.m_233856_(BlockStatePredictionHandler.java:44)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_233651_(ClientLevel.java:129)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_214108_(ClientPacketListener.java:2109)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundBlockChangedAckPacket.m_5797_(ClientboundBlockChangedAckPacket.java:19)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundBlockChangedAckPacket.m_5797_(ClientboundBlockChangedAckPacket.java:6)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
[24/02/2023 22:36:41 PM] at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
[24/02/2023 22:36:41 PM] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24/02/2023 22:36:41 PM] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[24/02/2023 22:36:41 PM] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24/02/2023 22:36:41 PM] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[24/02/2023 22:36:41 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[24/02/2023 22:36:42 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[24/02/2023 22:36:42 PM] at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[24/02/2023 22:36:42 PM] at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[24/02/2023 22:36:42 PM] [Render thread/FATAL] Error executing task on Client

### Reproduction Steps

1. in multiplayer, select an area and /set with modded block, not any of the vanilla assets.
2. you will see that nothing is changed, the console will show the lines of code above.
3. other player in the world see nothing as well.
4. teleport far away, and come back, the block will show.
5. same with manually placing/breaking blocks.

**Comment by octylFractal** [comment]
Can you attach the `latest.log` so we can see the full error?

**Comment by ink717** [comment]
[latest.log](https://github.com/EngineHub/WorldEdit/files/10830193/latest.log)

At the very end of the log, there were numerous similar error outputs. some were caused by worldedit action, some were manual block placements.

**Comment by octylFractal** [comment]
Can you narrow down a specific mod that this occurs with? And ensure that it still happens if you have _only_ WorldEdit and that mod installed?

**Comment by ink717** [comment]
> Can you narrow down a specific mod that this occurs with? And ensure that it still happens if you have _only_ WorldEdit and that mod installed?

We found out that’s it’s a bug from Minecraft itself. Mojang will fix it either in 1.19.4 or 1.20.
