### ISSUE TITLE
Creating a new session fails

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/WorldEdit#2291]
### WorldEdit Version

Bukkit-Official(7.3.0-SNAPSHOT+6371-df3f7b2)

### Platform Version

git-Paper-477 (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When you start to edit with worldedit it tries to save the season this fails with an error meassage

![Snag_7a8981](https://user-images.githubusercontent.com/12080017/228647604-ce2b4289-e7da-4d54-b63c-4c57e29ba1fe.png)
![Snag_7ae1b3](https://user-images.githubusercontent.com/12080017/228647685-61a3563d-15ca-46a6-990f-29dc1d6a4884.png)

### Expected Behavior

it should create the while an works

### Reproduction Steps

login with latest spigot 1.19.4 and latest we build

### Anything Else?

Error from Console

```
[21:26:32 INFO]: Cloude_Lecaw issued server command: //wand
>....
[21:26:32 WARN]: Failed to load saved session
java.nio.file.NoSuchFileException: plugins/WorldEdit/sessions/f24df990-9c6b-4f32-938a-4c91a26d31f4.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2922) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2955) ~[?:?]
	at com.sk89q.worldedit.session.storage.JsonFileSessionStore.load(JsonFileSessionStore.java:97) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:166) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[WorldEdit_7.3.0-Build6371.jar:?]
	
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(Miat net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	
>....at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[WorldEdit_7.3.0-Build6371.jar:?]
		at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2280) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2240) ~[?:?]Map.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-477]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-477]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:390) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[WorldEdit_7.3.0-Build6371.jar:?]
	at org.bukkit.command.SimpleCommandnecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-477]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-477]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by octylFractal** [comment]
IIRC this means that you don't have permission to write to that folder. You probably shouldn't be using 7.3.0 snapshots though.

**Comment by CloudeLecaw** [comment]
snapshots are there to test arround.
So the isssue is worldedit does not has access to create files in the season folder?

**Comment by octylFractal** [comment]
Likely, yes.
