### ISSUE TITLE
java.lang.ExceptionInInitializerError:Null 

### ISSUE THREAD

**Issue by DejmiNotHere** [EngineHub/WorldEdit#2335]
### WorldEdit Version

7.2.10

### Platform Version

spigot

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

so when I press /set air it says java.lang.ExceptionInInitializerError:Null and it says that report this bug, and there is more information in the console

What it says: java.lang.ExceptionInInitializerError:Null

console bug: 
[17:11:21] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.extent.reorder.MultiStageReorder
	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:269) ~[?:?]
	at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1048) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:249) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:248) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
	at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
	at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.extract$editSession(RegionCommandsRegistration.java:647) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_set(RegionCommandsRegistration.java:408) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:825) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1956) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1795) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1776) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1196) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1175) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1168) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1152) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1057) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.util.NoSuchElementException: No value present [in thread "Server thread"]
	at java.util.Optional.get(Optional.java:143) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.tag.CraftTag.getHandle(CraftTag.java:25) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at org.bukkit.craftbukkit.v1_18_R2.tag.CraftBlockTag.getValues(CraftBlockTag.java:25) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3445-Spigot-fb0dd5f-05a38da]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getFromBukkitTag(BukkitBlockCategoryRegistry.java:38) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:51) ~[?:?]
	at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[?:?]
	at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:46) ~[?:?]
	at com.sk89q.worldedit.registry.Category.getAll(Category.java:40) ~[?:?]
	at com.sk89q.worldedit.extent.reorder.MultiStageReorder.<clinit>(MultiStageReorder.java:68) ~[?:?]
	... 54 more

### Expected Behavior

I expect it to delete the space I selected into air to build something

### Reproduction Steps

1. ...?
2. ...?

**Comment by wizjany** [comment]
don't lie on the template
