### ISSUE TITLE
I cant paste a schem

### ISSUE THREAD

**Issue by Mohammedrida1010** [EngineHub/WorldEdit#2377]
### WorldEdit Version

7.2.15+6463-5ca4dff

### Platform Version

bukkit

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[13:50:14 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3.getFullBlock(Spigot_v1_16_R3.java:372) ~[?:?]
        at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:489) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getFullBlock(WatchdogTickingExtent.java:108) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.cache.LastAccessExtentCache.getFullBlock(LastAccessExtentCache.java:66) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractBufferingExtent.getFullBlock(AbstractBufferingExtent.java:68) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.world.WatchdogTickingExtent.getFullBlock(WatchdogTickingExtent.java:108) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.getFullBlock(AbstractDelegateExtent.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.ChangeSetExtent.setBlock(ChangeSetExtent.java:64) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.MaskingExtent.setBlock(MaskingExtent.java:69) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.validation.BlockChangeLimiter.setBlock(BlockChangeLimiter.java:87) ~[?:?]
        at com.sk89q.worldedit.extent.AbstractDelegateExtent.setBlock(AbstractDelegateExtent.java:78) ~[?:?]
        at com.sk89q.worldedit.extent.validation.DataValidatorExtent.setBlock(DataValidatorExtent.java:64) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:737) ~[?:?]
        at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:780) ~[?:?]
        at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:79) ~[?:?]
        at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
        at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
        at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
        at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:184) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:260) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:390) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:774) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1826) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1663) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:936) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:919) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:913) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:899) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:819) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]

### Expected Behavior

 paste the schem 

### Reproduction Steps

1. ...
2. ...
none

### Anything Else?

https://www.planetminecraft.com/project/pirate-island-spawn-v1/ this is my schem

**Comment by Joo200** [comment]
Don't lie on the issue template:

>  I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
> I am using the most recent Minecraft release.

From your stacktrace it's obviously you're on 1.16 with some hybrid server.
