### ISSUE TITLE
Worldedit //copy and //green doesn't work

### ISSUE THREAD

**Issue by Boredflea** [EngineHub/WorldEdit#2432]
### WorldEdit Version

7.3.0

### Platform Version

spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

whenever I use //green or //copy I get a bunch of error messages
//Green:An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
        at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:376) ~[?:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:306) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1123) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:258) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:257) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.extract$editSession(UtilityCommandsRegistration.java:672) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$green(UtilityCommandsRegistration.java:582) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:856) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:04:44] [Server thread/INFO]: Please report this error: [See console]
[18:04:44] [Server thread/INFO]: java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
//Copy: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
        at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:376) ~[?:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:306) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1123) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:258) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:257) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.extract$editSession(ClipboardCommandsRegistration.java:326) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:232) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:856) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:17:00] [Server thread/INFO]: Please report this error: [See console]
[18:17:00] [Server thread/INFO]: java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!

### Expected Behavior

//green: dirt blocks turn into grass block
//copy to copy selected region to clipboard

### Reproduction Steps

1. press /
2. press / again
3. type copy or green

### Anything Else?

My Minecraft spigot version is 1.20.1 and am running a server hosted by extra vm

**Comment by me4502** [comment]
Please provide your full logs, the copy command is one of the most frequently used commands and is used in testing, so this isn't reproducible as-is.

Also provide the actual worldedit version, 7.3.0 doesn't exist yet

**Comment by Boredflea** [comment]
I copied it directly from the console logs

**Comment by octylFractal** [comment]
Okay, but we still want to see all of the logs, not just the stack trace

**Comment by Boredflea** [comment]
container@pterodactyl~ Server marked as running...
[13:28:45] [Server thread/INFO]: /unstuck: Escape from being stuck inside a block
[13:28:45] [Server thread/INFO]: /up: Go upwards some distance
[13:28:45] [Server thread/INFO]: /version: Gets the version of this server including any plugins in use
[13:28:45] [Server thread/INFO]: /w: A Mojang provided command.
[13:28:45] [Server thread/INFO]: /weather: A Mojang provided command.
[13:28:45] [Server thread/INFO]: /whitelist: A Mojang provided command.
[13:28:45] [Server thread/INFO]: /worldborder: A Mojang provided command.
[13:28:45] [Server thread/INFO]: /worldedit: WorldEdit commands
[13:28:45] [Server thread/INFO]: /xp: A Mojang provided command.
>help return
[13:29:31] [Server thread/INFO]: --------- Help: /return -------------------------
[13:29:31] [Server thread/INFO]: Description: A Mojang provided command.
[13:29:31] [Server thread/INFO]: Usage: return
>/green
[18:04:44] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
        at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:376) ~[?:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:306) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1123) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:258) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:257) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.extract$editSession(UtilityCommandsRegistration.java:672) ~[?:?]
        at com.sk89q.worldedit.command.UtilityCommandsRegistration.cmd$green(UtilityCommandsRegistration.java:582) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:856) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:04:44] [Server thread/INFO]: Please report this error: [See console]
[18:04:44] [Server thread/INFO]: java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
>plugins
[18:13:50] [Server thread/INFO]: Plugins (4): SetHome, WorldEdit, SuperVanish, PlayerInvSee
>plugins worldedit
[18:14:01] [Server thread/INFO]: Plugins (4): SetHome, WorldEdit, SuperVanish, PlayerInvSee
>we version
[18:14:42] [Server thread/INFO]: WorldEdit version 7.3.0-beta-02
[18:14:42] [Server thread/INFO]: https://github.com/EngineHub/WorldEdit/
[18:14:42] [Server thread/INFO]: ------------------ Platforms ------------------
[18:14:42] [Server thread/INFO]: * Bukkit-Official(7.3.0-beta-02+e11f161)
[18:14:42] [Server thread/INFO]: 
[18:14:42] [Server thread/INFO]: ---------------- Capabilities ----------------
[18:14:42] [Server thread/INFO]: GAME_HOOKS: Bukkit-Official
[18:14:42] [Server thread/INFO]: CONFIGURATION: Bukkit-Official
[18:14:42] [Server thread/INFO]: USER_COMMANDS: Bukkit-Official
[18:14:42] [Server thread/INFO]: PERMISSIONS: Bukkit-Official
[18:14:42] [Server thread/INFO]: WORLDEDIT_CUI: Bukkit-Official
[18:14:42] [Server thread/INFO]: WORLD_EDITING: Bukkit-Official
[18:14:42] [Server thread/INFO]: 
>//copy
[18:16:47] [Server thread/INFO]: Unknown command. Type "/help" for help.
>/copy
[18:17:00] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
        at com.sk89q.worldedit.EditSession.setReorderMode(EditSession.java:376) ~[?:?]
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:306) ~[?:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[?:?]
        at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:1123) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$4(PlatformCommandManager.java:258) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:257) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
        at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
        at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.extract$editSession(ClipboardCommandsRegistration.java:326) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:232) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:856) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3815-Spigot-64b565e-9f64f0d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:17:00] [Server thread/INFO]: Please report this error: [See console]
[18:17:00] [Server thread/INFO]: java.lang.IllegalArgumentException: An EditSession without a fast mode tried to use it for reordering!
>worldedit:vs
[18:45:54] [Server thread/INFO]: Unknown command. Type "/help" for help.
>worldeit:version
[18:46:06] [Server thread/INFO]: Unknown command. Type "/help" for help.
>worldedit
[18:46:15] [Server thread/INFO]: No sub-command provided. Options: help, version, trace, reload, cui, tz, report
[18:46:15] [Server thread/INFO]: Usage: /worldedit <help|version|trace|reload|cui|tz|report>
>worldedit version
[18:46:30] [Server thread/INFO]: WorldEdit version 7.3.0-beta-02
[18:46:30] [Server thread/INFO]: https://github.com/EngineHub/WorldEdit/
[18:46:30] [Server thread/INFO]: ------------------ Platforms ------------------
[18:46:30] [Server thread/INFO]: * Bukkit-Official(7.3.0-beta-02+e11f161)
[18:46:30] [Server thread/INFO]: 
[18:46:30] [Server thread/INFO]: ---------------- Capabilities ----------------
[18:46:30] [Server thread/INFO]: GAME_HOOKS: Bukkit-Official
[18:46:30] [Server thread/INFO]: CONFIGURATION: Bukkit-Official
[18:46:30] [Server thread/INFO]: USER_COMMANDS: Bukkit-Official
[18:46:30] [Server thread/INFO]: PERMISSIONS: Bukkit-Official
[18:46:30] [Server thread/INFO]: WORLDEDIT_CUI: Bukkit-Official
[18:46:30] [Server thread/INFO]: WORLD_EDITING: Bukkit-Official
[18:46:30] [Server thread/INFO]:

**Comment by Boredflea** [comment]
there's the full logs

**Comment by Boredflea** [comment]
I'll just download a slightly older version
