### ISSUE TITLE
Mod fails at snapshot 23w43a

### ISSUE THREAD

**Issue by Maescool** [EngineHub/WorldEdit#2436]
### WorldEdit Version

7.3.0-beta-02

### Platform Version

Fabric

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Mod fails to load with the 23w43a, the mod was working on 23w42a

### Expected Behavior

the mod loading

### Reproduction Steps

1. install snapshot  23w43a with fabric loader and latest fabric api for this snapshot
2. add the mod
3. start the server

### Anything Else?

Log

> [00:52:27] [main/INFO]: Loading Minecraft 23w43a with Fabric Loader 0.14.24
[00:52:27] [ForkJoinPool-1-worker-3/WARN]: Mod voicechat uses the version 23w43a-2.4.27 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '23w43a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[00:52:27] [main/INFO]: Loading 42 mods:
	- fabric-api 0.90.5+1.20.3
	   |-- fabric-api-base 0.4.34+fce67b32c5
	   |-- fabric-api-lookup-api-v1 1.6.44+9468a19dc5
	   |-- fabric-biome-api-v1 13.0.14+9468a19dc5
	   |-- fabric-block-api-v1 1.0.13+73761d2ec5
	   |-- fabric-block-view-api-v2 1.0.2+73761d2ec5
	   |-- fabric-blockrenderlayer-v1 1.1.44+f4b7e424c5
	   |-- fabric-client-tags-api-v1 1.1.5+86b12645c5
	   |-- fabric-command-api-v1 1.2.38+f71b366fc5
	   |-- fabric-command-api-v2 2.2.17+9468a19dc5
	   |-- fabric-commands-v0 0.2.55+df3654b3c5
	   |-- fabric-containers-v0 0.1.74+df3654b3c5
	   |-- fabric-content-registries-v0 5.0.7+9468a19dc5
	   |-- fabric-convention-tags-v1 1.5.8+9468a19dc5
	   |-- fabric-crash-report-info-v1 0.2.21+f4b7e424c5
	   |-- fabric-data-generation-api-v1 13.1.7+3b908f6ac5
	   |-- fabric-dimensions-v1 2.1.57+9468a19dc5
	   |-- fabric-entity-events-v1 1.5.26+9468a19dc5
	   |-- fabric-events-interaction-v0 0.6.13+9468a19dc5
	   |-- fabric-events-lifecycle-v0 0.2.70+df3654b3c5
	   |-- fabric-game-rule-api-v1 1.0.41+9468a19dc5
	   |-- fabric-item-api-v1 2.1.33+9468a19dc5
	   |-- fabric-item-group-api-v1 4.0.16+ebb15496c5
	   |-- fabric-key-binding-api-v1 1.0.39+f4b7e424c5
	   |-- fabric-keybindings-v0 0.2.37+df3654b3c5
	   |-- fabric-lifecycle-events-v1 2.2.28+9468a19dc5
	   |-- fabric-loot-api-v2 2.1.2+6f9f09e0c5
	   |-- fabric-message-api-v1 6.0.3+ebb15496c5
	   |-- fabric-mining-level-api-v1 2.1.57+f4b7e424c5
	   |-- fabric-model-loading-api-v1 1.0.6+9468a19dc5
	   |-- fabric-models-v0 0.4.5+9386d8a7c5
	   |-- fabric-networking-api-v1 3.0.10+9468a19dc5
	   |-- fabric-object-builder-api-v1 13.0.3+acb5cc4ec5
	   |-- fabric-particles-v1 1.1.5+f4b7e424c5
	   |-- fabric-recipe-api-v1 2.0.7+9468a19dc5
	   |-- fabric-registry-sync-v0 4.0.6+9468a19dc5
	   |-- fabric-renderer-api-v1 3.2.2+2034447cc5
	   |-- fabric-renderer-indigo 1.5.2+2034447cc5
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3c5
	   |-- fabric-rendering-data-attachment-v1 0.3.40+73761d2ec5
	   |-- fabric-rendering-fluids-v1 3.0.31+f4b7e424c5
	   |-- fabric-rendering-v0 1.1.52+df3654b3c5
	   |-- fabric-rendering-v1 3.0.11+9468a19dc5
	   |-- fabric-resource-conditions-api-v1 2.3.11+ebb15496c5
	   |-- fabric-resource-loader-v0 0.11.13+9468a19dc5
	   |-- fabric-screen-api-v1 2.0.13+9468a19dc5
	   |-- fabric-screen-handler-api-v1 1.3.43+9468a19dc5
	   |-- fabric-sound-api-v1 1.0.15+f4b7e424c5
	   |-- fabric-transfer-api-v1 4.0.2+9468a19dc5
	   \-- fabric-transitive-access-wideners-v1 5.0.8+3b908f6ac5
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.20.3-alpha.23.43.a
	- voicechat 23w43a-2.4.27
	   \-- fabric-key-binding-api-v1 1.0.39+f4b7e424cb
	- worldedit 7.2.17+6544-56d0383
[00:52:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[00:52:27] [main/INFO]: Compatibility level set to JAVA_16
[00:52:27] [main/INFO]: Compatibility level set to JAVA_17
[00:52:31] [main/ERROR]: Mixin apply for mod worldedit failed worldedit-fabric.mixins.json:MixinMinecraftServer from mod worldedit -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$1(ServerLifecycleEvents.java:36) ~[fabric-lifecycle-events-v1-2.2.2+9468a19dc5-40f5f194fda22a45.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.<clinit>(ServerLifecycleEvents.java:36) ~[fabric-lifecycle-events-v1-2.2.2+9468a19dc5-40f5f194fda22a45.jar:?]
	at net.fabricmc.fabric.impl.lookup.ApiLookupImpl.onInitialize(ApiLookupImpl.java:26) ~[fabric-api-lookup-api-v1-1.6.44+9468a19dc5-df4c1081c08bf584.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.23w43a-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
[00:52:31] [main/ERROR]: Mixin apply for mod worldedit failed worldedit-fabric.mixins.json:MixinMinecraftServer from mod worldedit -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$1(ServerWorldEvents.java:32) ~[fabric-lifecycle-events-v1-2.2.2+9468a19dc5-40f5f194fda22a45.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.34+fce67b32c5-d77483301fb6c14b.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.<clinit>(ServerWorldEvents.java:32) ~[fabric-lifecycle-events-v1-2.2.2+9468a19dc5-40f5f194fda22a45.jar:?]
	at net.fabricmc.fabric.impl.event.lifecycle.LifecycleEventsImpl.onInitialize(LifecycleEventsImpl.java:50) ~[fabric-lifecycle-events-v1-2.2.2+9468a19dc5-40f5f194fda22a45.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.23w43a-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
[00:52:31] [main/ERROR]: Mixin apply for mod worldedit failed worldedit-fabric.mixins.json:MixinMinecraftServer from mod worldedit -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @ shadow field field_4571 was not located in the target class net.minecraft.server.MinecraftServer. Using refmap worldedit-fabric-mc1.20.2-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.23w43a-loader.0.14.24-launcher.0.11.2.jar:0.11.2]

**Comment by me4502** [comment]
This is not a bug, you’re using a version of worldedit that doesn’t support your MC version.
