### ISSUE TITLE
java.lang.IllegalAccessError:

### ISSUE THREAD

**Issue by Egemenbdk** [EngineHub/WorldEdit#2450]
### WorldEdit Version

7.3.0 Beta

### Platform Version

Spigot

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

i tried copying a build, error:
`java.lang.IllegalAccessError: class com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter tried to access private field net.minecraft.nbt.NBTTagCompound.x (com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6838bde1; net.minecraft.nbt.NBTTagCompound is in unnamed module of loader java.net.URLClassLoader @242b836)
at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter.toNative(PaperweightAdapter.java:1002) ~[?:?]
at com.sk89q.worldedit.bukkit.adapter.impl.v1_20_R3.PaperweightAdapter.lambda$getFullBlock$1(PaperweightAdapter.java:397) ~[?:?]
at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:83) ~[?:?]
at com.sk89q.worldedit.world.NbtValued.getNbt(NbtValued.java:119) ~[?:?]
at com.sk89q.worldedit.function.block.ExtentBlockCopy.transformNbtData(ExtentBlockCopy.java:90) ~[?:?]
at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:77) ~[?:?]
at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[?:?]
at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[?:?]
at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[?:?]
at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.java:106) ~[?:?]
at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(ClipboardCommandsRegistration.java:232) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:877) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:413) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:335) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1853) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1815) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1197) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1176) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1169) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1153) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3972-Spigot-ce0f71e-c00438b]
at java.lang.Thread.run(Thread.java:840) ~[?:?]`

### Expected Behavior

it was supposed to copy after typing //copy

### Reproduction Steps

1. choose an area with the wand using right and left click
2. type //copy in chat

**Comment by octylFractal** [comment]
Which beta? There are multiple. Only Beta 3 works for 1.20.4.
