### ISSUE TITLE
Hopper / Hopper minecart not working with a filled Decorated Pot

### ISSUE THREAD

**Issue by thunderlight411** [EngineHub/WorldEdit#2456]
### WorldEdit Version

7.2.19-Snapshot+6617-6a5a500

### Platform Version

git-Paper-349 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: dc62150)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

hopper under a decorated pot is not removing the items from the Pot when a item is put into the Decorated Pot.
Interface from Hopper closes when opend

[10:56:58] [Server thread/ERROR]: BlockEntity threw exception at world:2706,65,-285
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryHolder.getInventory()" because the return value of "net.minecraft.world.level.block.entity.TileEntity.getOwner(boolean)" is null
	at net.minecraft.world.level.block.entity.HopperBlockEntity.getInventory(HopperBlockEntity.java:377) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.callPullMoveEvent(HopperBlockEntity.java:350) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPull(HopperBlockEntity.java:293) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.suckInItems(HopperBlockEntity.java:545) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.lambda$pushItemsTick$0(HopperBlockEntity.java:144) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:205) ~[?:?]
	at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:143) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1171) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1123) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1295) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:926) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1717) ~[paper-1.20.4.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

When a hopper minecarts moved under a filled decorated pot the hopper minecart is instantly removed from the world when there is a item inside the decorated pot

### Expected Behavior

Hopper to be able to remove items from the pot like as this is a vanilla behavior

### Reproduction Steps

1. Place a hopper
2. place a decorated pot on the hopper
3. Fill the decorated pot with any item
4. try to open the hoper.

and for the hopper minecraft
1. place some rails
2. place a Hopper minecart
3. place a decorated pot on top of the Hopper minecart
4. Fill the Decorated Pot with any item
5. Hopper minecraft disapears instantly

**Comment by me4502** [comment]
How is this in any way related to WorldEdit?

**Comment by thunderlight411** [comment]
This issue only accours when worldedit is loaded.
even when WorldEdit is the only plugin that is loaded in the server

**Comment by me4502** [comment]
WorldEdit doesn't alter behaviour of the game at all, nor touch hopper carts. It's only doing things when edits are being made. The error also doesn't indicate it's related to WorldEdit at all.

Unless you can provide reproduction steps that prove it's related to WorldEdit, this looks like a bug in either Minecraft or your server software.

**Comment by thunderlight411** [comment]
Sorry i'm posting it in the wrong section its a related to WG.
Will create a new ticket over there
