### ISSUE TITLE
Can't replace leaves to leaves from TerraFirmaCraft

### ISSUE THREAD

**Issue by Proxwian** [EngineHub/WorldEdit#2463]
### WorldEdit Version

7.2.15

### Platform Version

Forge 47.2.20

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I try to replace blocks with TFC leaves, it doesn't work and give me error in console

### Expected Behavior

//replace command works as intended

### Reproduction Steps

1. Select territory with any minecraft leaves blocks
2. Try to replace it with leaves from TFC
3. Get error below

### Anything Else?

`[10:18:09] [Server thread/ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalArgumentException: tfc:wood/leaves/chestnut has no state for {IntegerProperty{name=distance}=1, com.sk89q.worldedit.forge.internal.IPropertyAdapter@5d039ca=FluidKey[minecraft:empty], BooleanProperty{name=persistent}=false}
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.1-jre.jar%23104!/:?]
	at com.sk89q.worldedit.world.block.BlockType.getState(BlockType.java:185) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.forge.internal.ForgeTransmogrifier.transmogToWorldEdit(ForgeTransmogrifier.java:123) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.forge.ForgeAdapter.adapt(ForgeAdapter.java:193) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.forge.ForgeWorldEdit.lambda$setupRegistries$3(ForgeWorldEdit.java:182) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:85) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:101) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:331) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at com.sk89q.worldedit.forge.__ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic) ~[worldedit-mod-7.2.15.jar%23434!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraft.commands.Commands.m_242674_(Commands.java:249) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.lang.IllegalArgumentException: tfc:wood/leaves/chestnut has no state for {IntegerProperty{name=distance}=1, com.sk89q.worldedit.forge.internal.IPropertyAdapter@5d039ca=FluidKey[minecraft:empty], BooleanProperty{name=persistent}=false}
		at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.1-jre.jar%23104!/:?]
		at com.sk89q.worldedit.world.block.BlockType.getState(BlockType.java:185) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.forge.internal.ForgeTransmogrifier.transmogToWorldEdit(ForgeTransmogrifier.java:123) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.forge.ForgeAdapter.adapt(ForgeAdapter.java:193) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.forge.ForgeWorldEdit.lambda$setupRegistries$3(ForgeWorldEdit.java:182) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.world.block.BlockType.computeDefaultState(BlockType.java:85) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.util.concurrency.LazyReference.getValue(LazyReference.java:68) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.world.block.BlockType.getDefaultState(BlockType.java:162) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseLogic(DefaultBlockParser.java:354) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:93) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.factory.parser.DefaultBlockParser.parseFromInput(DefaultBlockParser.java:63) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:43) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.factory.parser.pattern.SingleBlockPatternParser.parseFromInput(SingleBlockPatternParser.java:30) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.internal.registry.AbstractFactory.parseFromInput(AbstractFactory.java:77) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.command.argument.FactoryConverter.convert(FactoryConverter.java:126) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at org.enginehub.piston.impl.CommandParser.lambda$isAcceptedByTypeParsers$7(CommandParser.java:497) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
		at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
		at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
		at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
		at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
		at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
		at org.enginehub.piston.impl.CommandParser.isAcceptedByTypeParsers(CommandParser.java:492) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at org.enginehub.piston.impl.CommandParser.parseRegularArgument(CommandParser.java:429) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at org.enginehub.piston.impl.CommandParser.parse(CommandParser.java:340) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at org.enginehub.piston.impl.CommandManagerImpl.parse(CommandManagerImpl.java:240) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at org.enginehub.piston.CommandManager.execute(CommandManager.java:154) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.forge.ForgeWorldEdit.onCommandEvent(ForgeWorldEdit.java:331) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at com.sk89q.worldedit.forge.__ForgeWorldEdit_onCommandEvent_CommandEvent.invoke(.dynamic) ~[worldedit-mod-7.2.15.jar%23434!/:?]
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2381!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2381!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2381!/:?]
		at net.minecraft.commands.Commands.m_242674_(Commands.java:249) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
		at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23437!/:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:18:09] [Render thread/INFO]: [System] [CHAT] Пожалуйста, сообщите об этой ошибке: [Смотрите консоль]
[10:18:09] [Render thread/INFO]: [System] [CHAT] java.lang.IllegalArgumentException: tfc:wood/leaves/chestnut has no state for {IntegerProperty{name=distance}=1, com.sk89q.worldedit.forge.internal.IPropertyAdapter@5d039ca=FluidKey[minecraft:empty], BooleanProperty{name=persistent}=false}`

**Comment by Proxwian** [comment]
WDYM lie? Where I was wrong? Learn how to talk to people

**Comment by octylFractal** [comment]
You checked:
> I am using the most recent Minecraft release.

You are not, it is 1.20.4 right now.

**Comment by octylFractal** [comment]
However, I still think this might be a valid issue. Leaving it open for investigation.
