### ISSUE TITLE
//regen not working

### ISSUE THREAD

**Issue by JesseMotaMendonca** [EngineHub/WorldEdit#2467]
### WorldEdit Version

7.3.0-beta-04

### Platform Version

1.20.4

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

when i try to //regen "Unable to regenerate chuncks. Check console for details":
[15:34:54] [Server thread/INFO]: Polimpo4 issued server command: //regen
[15:34:54] [Server thread/WARN]: Regeneration via adapter failed.
java.lang.UnsupportedOperationException: Missing BukkitImplAdapter for this version.
        at com.sk89q.worldedit.bukkit.BukkitWorld.regenerate(BukkitWorld.java:196) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.regenerate(RegionCommands.java:456) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_regen(RegionCommandsRegistration.java:614) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:506) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:386) ~[?:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:861) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:413) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:335) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1833) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1795) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1155) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1134) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1111) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1025) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4038-Bukkit-22a541a]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Expected Behavior

Regenerate the area i selected

### Reproduction Steps

1. Select area with //wand axe
2. //regen

### Anything Else?

the //set command also not working

**Comment by Joo200** [comment]
CraftBukkit should not be used, it is not production software and not supported by either its developers or developers of plugins. It exists purely as a interim build step for Spigot, and the output jar is therefore a 'dev jar' and cannot run many production plugins. CraftBukkit has not been published since 1.7.10, and has been explicitly listed as unsupported by Spigot since 1.14. You should be running either Paper or Spigot.

For more information, see https://madelinemiller.dev/blog/stop-using-craftbukkit/
