### ISSUE TITLE
Can't load a schematic saved in fabric version of WorldEdit

### ISSUE THREAD

**Issue by Saidas25** [EngineHub/WorldEdit#2474]
### WorldEdit Version

Client: Fabric_Official(7.3.0-beta-04+c28ebca) Server: Bukkit-Official(7.2.18+6616-abda4e0)

### Platform Version

Fabric 1.20.4, Purpur 1.20.4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I saved a schematic of my server spawn in singleplayer, uploaded that .schem file to my server, did //schem load spawn. It did not work, i got Failed to load schematic: Unknown error. Please see console. In the console there is this:

[16:41:44] [Server thread/INFO]: Saidas25 issued server command: //schem load spawn
[16:41:44] [WorldEdit Task Executor - 3/ERROR]: Uncaught exception occurred in task: Loading schematic spawn
java.io.IOException: Schematic file is missing a "Version" tag of type com.sk89q.jnbt.IntTag
at com.sk89q.worldedit.extent.clipboard.io.NBTSchematicReader.requireTag(NBTSchematicReader.java:36) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.getBaseTag(SpongeSchematicReader.java:157) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:91) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:322) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:304) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.2.18-dist.jar:?]
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-32.1.2-jre.jar:?]
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75) ~[guava-32.1.2-jre.jar:?]
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-32.1.2-jre.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behavior

I expected my spawn to load, so i could paste it in with //paste

### Reproduction Steps

1. Save a schematic in a singleplayer world using fabric worldedit
2. Try to load it in a Paper/Purpur server
3. Get the error

**Comment by Saidas25** [comment]
> mismatched WE versions

what versions do i use
