### ISSUE TITLE
Unable to load any OLD schematic on latest DEV version (1.20.4)

### ISSUE THREAD

**Issue by Catzy44** [EngineHub/WorldEdit#2490]
### WorldEdit Version

7.3.0-SNAPSHOT 6678-55745ad

### Platform Version

paper spigot 1.20.4 450

### Confirmations

- [x] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have around 20 schematics created across different game versions, starting from 1.10 and ending on 1.20.2. I've just updated my server to the latest game version (1.20.4), then updated WorldEdit, and now I'm unable to load any schematic created in different game version than current.

The game shows: Failed to load schematic: Unknown error
There is stacktrace from server console: 
`[05:11:11 INFO]: PrzemoVi issued server command: /schematic load spawn schematic
[05:11:11 ERROR]: Uncaught exception occurred in task: Loading schematic spawn
java.lang.IllegalArgumentException: Invalid NBT ID: 116
        at org.enginehub.linbus.common.LinTagId.fromId(LinTagId.java:87) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.stream.impl.LinNbtReader.nextOrNull(LinNbtReader.java:130) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.stream.impl.OptionalInfoCalculator.nextOrNull(OptionalInfoCalculator.java:67) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readCompound(LinTagReader.java:94) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readValue(LinTagReader.java:210) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readList(LinTagReader.java:189) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readValue(LinTagReader.java:216) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readList(LinTagReader.java:189) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readValue(LinTagReader.java:216) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readCompound(LinTagReader.java:104) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readValue(LinTagReader.java:210) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readList(LinTagReader.java:189) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readValue(LinTagReader.java:216) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readCompound(LinTagReader.java:104) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.impl.LinTagReader.readRoot(LinTagReader.java:72) ~[worldedit-bukkit-7.3.0.jar:?]
        at org.enginehub.linbus.tree.LinRootEntry.readFrom(LinRootEntry.java:52) ~[worldedit-bukkit-7.3.0.jar:?]
        at com.sk89q.worldedit.extent.clipboard.io.MCEditSchematicReader.read(MCEditSchematicReader.java:116) ~[worldedit-bukkit-7.3.0.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[worldedit-bukkit-7.3.0.jar:?]
        at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[worldedit-bukkit-7.3.0.jar:?]
        at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-bukkit-7.3.0.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-32.1.2-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]`

I've noticed something new: The new WE version is asking for a schematic type. I've tried all the types suggested by command autocompletion, but none of them seem to work. By the way, the plugin suggests possible schematic format types for the second and third arguments (schematic name and schematic type), the schematic name suggestion isn't functioning. Schematic name suggestion is replaced with type suggestion.

Thanks for your time

### Expected Behavior

n/a

### Reproduction Steps

1. Use latest paperspigot (not tested other engines)
2. Use latest DEV worldedit version
3. Try to load any schematic generated on older game version

**Comment by me4502** [comment]
The error you're showing indicates something is wrong with the file. Also the version you've put down isn't a version that exists, and definitely isn't the latest dev version.
