### ISSUE TITLE
Not all platforms have been registered yet! Please wait until WorldEdit is initialized.

### ISSUE THREAD

**Issue by IssueDescription** [EngineHub/WorldEdit#2535]
### WorldEdit Version

worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar still happens on latest bukkit.org dl tho

### Platform Version

Paper-1.20.6-86 (latest)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Upon server boot:

Dist:

```
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until WorldEdit is initialized.
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:170) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:296) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:793) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.worldedit.bukkit.BukkitCommandInspector.getShortText(BukkitCommandInspector.java:56) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic.<init>(DynamicPluginCommandHelpTopic.java:44) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic$Factory.createTopic(DynamicPluginCommandHelpTopic.java:144) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic$Factory.createTopic(DynamicPluginCommandHelpTopic.java:141) ~[worldedit-bukkit-7.3.1-SNAPSHOT-dist.jar:?]
        at org.bukkit.craftbukkit.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:136) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-5a9afbe]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
        
        
        
  Snapshot:
        
   ```
     [12:45:00 ERROR]: Encountered an unexpected exception
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until WorldEdit is initialized.
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:170) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.worldedit.extension.platform.PlatformManager.getConfiguration(PlatformManager.java:296) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.worldedit.WorldEdit.getConfiguration(WorldEdit.java:793) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.worldedit.bukkit.BukkitCommandInspector.getShortText(BukkitCommandInspector.java:56) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic.<init>(DynamicPluginCommandHelpTopic.java:44) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic$Factory.createTopic(DynamicPluginCommandHelpTopic.java:144) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar/com.sk89q.bukkit.util.DynamicPluginCommandHelpTopic$Factory.createTopic(DynamicPluginCommandHelpTopic.java:141) ~[worldedit-bukkit-7.3.3-SNAPSHOT-dist (1).jar:?]
        at org.bukkit.craftbukkit.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:136) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-9bf4855]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:45:00 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-05-21_12.45.00-server.txt
```

### Expected Behavior

Should work.

### Reproduction Steps

Try to load any version of worldedit on latest paper

**Comment by me4502** [comment]
You need to provide your full logs, there's nothing that can be said based on what you've provided

**Comment by me4502** [comment]
That looks like you're running an unobfuscated Paper jar, which won't work. you need to run an actual release copy of Paper, not a development one

**Comment by me4502** [comment]
Not in the way that dev jars are. either way there’s something very off about your server, and without your full logs we can’t say much further. I can’t reproduce this issue given i ran the latest release on latest Paper just hours ago fine, so the issue would be in your server setup somewhere

**Comment by wizjany** [comment]
that's still not your full log.

**Comment by me4502** [comment]
That’s irrelevant and incorrect. If you want help, provide your logs. Otherwise this ticket will be locked

**Comment by me4502** [comment]
There are a few oddities in the various logs you’ve posted. this very much feels like you’re not telling us something very important.

My assumption is you’re running this via an IDE, which doesn’t have many of the necessary rewrites enabled for plugins to function. The main one that’s very evident by your logs, is the one that hides legacy materials when iterating over the available materials.

**Comment by me4502** [comment]
I’m not talking about plugin rewriting.
