### ISSUE TITLE
Paper 1.20.6 - WorldEdit does not contain a paper-plugin.yml or plugin.yml

### ISSUE THREAD

**Issue by mddunner** [EngineHub/WorldEdit#2536]
### WorldEdit Version

worldedit-mod-7.3.2

### Platform Version

paper-1.20.6-88

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

After updating my server to the latest 1.20.6 and WorldEdit 7.3.2, WorldEdit fails to load. This error is seen in the logs. I have tried deleting my plugins folder and re-adding the plugin JAR files. 

[07:47:31] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/worldedit-mod-7.3.2.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/worldedit-mod-7.3.2.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:81) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/worldedit-mod-7.3.2.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	... 9 more

### Expected Behavior

Plugin loads successfully.

### Reproduction Steps

1. stop Paper server
2. update Paper server to latest 1.20.6 dev  build
3. update WorldEdit to 7.3.2
4. start paper server

### Anything Else?

Please let me know if there are additional logs I can provide or steps I can try! Thanks for your review!!

**Comment by me4502** [comment]
You're using the Fabric/NeoForge mod, not the Bukkit plugin.

**Comment by mddunner** [comment]
Wow, thanks for the fast response! That's a big miss on my side. Sorry about that... Loaded the Bukkit plugin without issue!

Please close this PEBKAC out.
