### ISSUE TITLE
WorldEdit not loading

### ISSUE THREAD

**Issue by maxtimbo** [EngineHub/WorldEdit#2577]
### WorldEdit Version

worldedit-bukkit-7.3.4

### Platform Version

paper-1.21-48

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I'm getting the following error:

```
[10:04:06 ERROR]: [EntrypointUtil] Failed to open plugin jar plugins/worldedit-bukkit-7.3.4.jar
java.lang.RuntimeException: Failed to open plugin jar plugins/worldedit-bukkit-7.3.4.jar
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:339) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.21.jar:1.21-48-70b0e84]
        at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.21.jar:1.21-48-70b0e84]
        at org.bukkit.craftbukkit.Main.main(Main.java:298) ~[paper-1.21.jar:1.21-48-70b0e84]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.findEND(Unknown Source) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(Unknown Source) ~[jdk.zipfs:?]
        at jdk.zipfs@21.0.3/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source) ~[jdk.zipfs:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
        at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
        at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:290) ~[paper-1.21.jar:1.21-48-70b0e84]
        ... 10 more
```

### Expected Behavior

the plugin to load

### Reproduction Steps

The server is a docker compose. If it makes sense to post the yml file, I'll do so in the comments.

**Comment by wizjany** [comment]
you have a broken jar file, not a worldedit bug

**Comment by maxtimbo** [comment]
> you have a broken jar file, not a worldedit bug

Do you mean the worledit jar is broken, or the papermc jar? I'm downloading from:
https://cdn.modrinth.com/data/1u6JkXh5/versions/vMrPkmgF/worldedit-bukkit-7.3.4.jar

PaperMC is downloading via the docker

**Comment by wizjany** [comment]
the one it specifically points out in the stacktrace you gave. either way this is not a support forum and as mentioned, not a worldedit bug.
