### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet com.google.common.collect.Sets.immutableEnumSet(java.lang.Object, java.lang.Object[])'

### ISSUE THREAD

**Issue by quinxero** [EngineHub/WorldEdit#2635]
### WorldEdit Version

7.3.x

### Platform Version

Spigot 1.21.1, java 22

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[2024-09-29 10:55:29.646 INFO  Server thread] com.sk89q.worldedit.bukkit.WorldEditPlugin: [WorldEdit] Loading WorldEdit v7.3.6+6892-3d660b8
[2024-09-29 10:55:30.905 ERROR Server thread] org.bukkit.craftbukkit.v1_21_R1.CraftServer: 'com.google.common.collect.ImmutableSet com.google.common.collect.Sets.immutableEnumSet(java.lang.Object, java.lang.Object[])' initializing WorldEdit v7.3.6+6892-3d660b8 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet com.google.common.collect.Sets.immutableEnumSet(java.lang.Object, java.lang.Object[])'
        at com.sk89q.worldedit.bukkit.BukkitServerInterface.<clinit>(BukkitServerInterface.java:233) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java:135) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:469) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[2024-09-29 10:55:30.911 INFO  Server thread] com.sk89q.worldedit.bukkit.WorldEditPlugin: [WorldEdit] Enabling WorldEdit v7.3.6+6892-3d660b8
[2024-09-29 10:55:30.946 INFO  Server thread] com.sk89q.wepif.PermissionsResolverManager: WEPIF: Using the Bukkit Permissions API.
[2024-09-29 10:55:31.407 ERROR Server thread] Minecraft: Error occurred while enabling WorldEdit v7.3.6+6892-3d660b8 (Is it up to date?)
com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until WorldEdit is initialized.
        at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:170) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:297) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:194) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4333-Spigot-a759b62-fc5b2d7]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

### Expected Behavior

That the server started without an error in the plugin. I did an installation with only the plugin and no other and the same error

### Reproduction Steps

1. put jar plugin into plugins folder
2. start server

**Comment by wizjany** [comment]
this is almost certainly an issue with your server/installation/setup. the guava class/method in that error is definitely present in the libraries used and provided by mojang/spigot.

**Comment by quinxero** [comment]
> this is almost certainly an issue with your server/installation/setup. the guava class/method in that error is definitely present in the libraries used and provided by mojang/spigot.

Thanks for the reply, I will check my server configuration.
