### ISSUE TITLE
/tree does not do anything

### ISSUE THREAD

**Issue by Archerymaister** [EngineHub/WorldEdit#2675]
### WorldEdit Version

Bukkit-Official(7.3.9+6959-7adf70b)

### Platform Version

Paper version 1.21.3-60-master

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Nothing happens when you right-click the item you bound the tool to. But there is a stacktrace in the logs.

```
[2024-12-08 20:25:07] [Server thread/ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.BlockInteractEvent@2e7e5745 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at WorldEdit.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.WorldEdit.handleBlockRightClick(WorldEdit.java:671) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:133) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1957) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
        at org.bukkit.craftbukkit.util.DummyGeneratorAccess.getRandom(DummyGeneratorAccess.java:103) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$updateShapeAtEdge$4(StructureTemplate.java:471) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllAxisFaces(DiscreteVoxelShape.java:267) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllFaces(DiscreteVoxelShape.java:246) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.updateShapeAtEdge(StructureTemplate.java:466) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.level.levelgen.feature.TreeFeature.lambda$place$9(TreeFeature.java:157) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.world.level.levelgen.feature.TreeFeature.place(TreeFeature.java:155) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:190) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:25) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at org.bukkit.craftbukkit.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:301) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at org.bukkit.craftbukkit.CraftRegionAccessor.generateTree(CraftRegionAccessor.java:204) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at WorldEdit.jar/com.sk89q.worldedit.bukkit.BukkitWorld.generateTree(BukkitWorld.java:278) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.util.TreeGenerator$TreeType.generate(TreeGenerator.java:156) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.command.tool.TreePlanter.actPrimary(TreePlanter.java:62) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.extension.platform.PlatformManager.handleBlockInteract(PlatformManager.java:397) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at WorldEdit.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 31 more
```

### Expected Behavior

The tree should be placed.

### Reproduction Steps

1. /tool tree birch
2. Rightclick

**Comment by octylFractal** [comment]
This is a bug in Paper, please report it to them. We just call `#generateTree` and are not responsible for that implementation.

**Comment by Archerymaister** [comment]
Okay, thank your for your response! I'll discuss it with them!

**Comment by wizjany** [comment]
Doesn't seem to be an issue anymore unless there's some specific repro not mentioned here.
