### ISSUE TITLE
1.21.4 doesnt work

### ISSUE THREAD

**Issue by TutorialMan7727** [EngineHub/WorldEdit#2680]
### WorldEdit Version

7.3.10-SNAPSHOT+6969-296928e

### Platform Version

Paper version 1.21.4-14-master@b746d9d (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Constant errrors on 1.21.4 such as 
```[16:43:59 ERROR]: Could not pass event BlockSpreadEvent to WorldGuard v7.0.13-beta-1+2f13ae0
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockSpread(WorldGuardBlockListener.java:553) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:967) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:951) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.level.block.SpreadingSnowyDirtBlock.randomTick(SpreadingSnowyDirtBlock.java:90) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1285) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:911) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:974) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:617) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:504) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:474) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:772) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1877) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1666) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_TRIM_TEMPLATES' [in thread "Server thread"]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:923) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onUseBlock$2(RegionProtectionListener.java:258) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at com.google.common.base.Predicate.test(Predicate.java:79) ~[guava-33.3.1-jre.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:252) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at worldguard-bukkit-7.0.13-beta-1-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityInteract(EventAbstractionListener.java:602) ~[worldguard-bukkit-7.0.13-beta-1-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor132.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.RedStoneOreBlock.stepOn(RedStoneOreBlock.java:60) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1362) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1353) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3670) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:682) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:268) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3317) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.Mob.tick(Mob.java:439) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:236) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1306) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1490) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:813) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:795) ~[paper-1.21.4.jar:1.21.4-14-b746d9d]
        ... 5 more
```

### Expected Behavior

For it to not give me errors

### Reproduction Steps

1. Install paper version
2. Get worldedit
3. CHeck the console

**Comment by octylFractal** [comment]
That error is clearly in WorldGuard, and you're not using a version of that which supports 1.21.4. Please try a dev build of WorldGuard that does support 1.21.4, or wait patiently for a release.

**Comment by TutorialMan7727** [comment]
Oh, sorry about that one. I'll pay attention more next time
